const translation = {
    // BCX
    "You can find BCX here ►": "从这里浏览BCX ►",
    "- Bondage Club Extended -": "- Bondage Club 拓展 -",
    "BCX TUTORIAL: Welcome": "BCX教程: 欢迎",
    "Loading...": "加载中...",
    "BCX TUTORIAL: Adding curses": "BCX教程: 添加诅咒",
    "BCX TUTORIAL: Quick overview": "BCX教程: 快速概述",
    "BCX TUTORIAL: End of introduction": "BCX教程: 介绍结束",
    "BCX TUTORIAL: Curses module overview": "BCX教程: 诅咒模块概述",
    "BCX TUTORIAL: New chat room icons": "BCX教程: 新的聊天室图标",
    "BCX TUTORIAL: Logging module screen": "BCX教程: 日志模块界面",
    "BCX TUTORIAL: Rules module overview": "BCX教程: 规则模块概述",
    "BCX TUTORIAL: Logging configuration screen": "BCX教程: 日志配置界面",
    "BCX TUTORIAL: Introduction to roles and permissions": "BCX教程: 角色和权限的介绍",
    "BCX TUTORIAL: Permission system base principles": "BCX教程: 权限系统的基本原理",
    "BCX TUTORIAL: Limiting curse slots / rules": "BCX教程: 限制诅咒 插槽/规则",
    "BCX TUTORIAL: General permission examples": "BCX教程: 一般权限示例",
    "BCX TUTORIAL: Permission setup example 1": "BCX教程: 权限设置示例1",
    "BCX TUTORIAL: Permission setup example 2": "BCX教程: 权限设置示例2",
    "BCX TUTORIAL: Permission system overview": "BCX教程: 权限系统概述",
    "BCX TUTORIAL: Commands module overview": "BCX教程: 指令模块概述",
    "BCX TUTORIAL: Trigger conditions": "BCX教程: 触发条件",
    "BCX TUTORIAL: Adding a rule": "BCX教程: 添加规则",
    "BCX TUTORIAL: Chat commands": "BCX教程: 聊天指令",
    "Please choose a preset, which sets your default experience, permissions and configuration.":
        "请选择一个预设,以设定您的默认体验、权限和配置.",
    "Note: You can change the defaults, but changing to another preset is not possible without resetting BCX fully.":
        "注意: 您可以更改默认值,但更改至另一个预设需要完全重置BCX.",
    "Dominant": "支配者",
    "This preset is for dominants who": "这个预设是为从不打算屈服的",
    "never intend to submit. Therefore,": "支配者准备的. 因此,",
    "most modules are not loaded at": "大多数模块在开始时都没有加载.",
    "start. That said, you can still use": "但是, 您仍然可以在其他",
    "the BCX graphical user interface": "BCX用户上操作",
    "on other BCX users to use actions,": "BCX用户界面,",
    "you have permission for, on them,": "您拥有其权限,",
    "same as with all other presets.": "就像使用所有其他预设一样.",
    "Switch/Exploring": "转换/探索者",
    "This preset is for switches who": "这个预设是给",
    "are sometimes dominant and": "有时想占主导地位,",
    "sometimes submissive, enabling": "有时想服从的转换者,",
    "them to explore BCX slowly, while": "使他们能够慢慢探索BCX,",
    "having full control over all of its": "因此, 转换者拥有完整的",
    "settings and features.": "设置和功能.",
    "Easily try out all features": "轻松尝试所有功能",
    "Submissive": "服从者",
    "This preset is for submissives,": "这个预设是为服从者准备的,",
    "who want to give some of their": "他们想把一些控制权",
    "control to selected dominants and": "交给选定的支配者和爱人,",
    "lovers, giving only them authority": "只给他们",
    "over some of BCX's settings. You": "'对BCX的一些设置的权力'",
    "can irreversably give away more": "当你想要的时候,你可以",
    "and more control, when you want.": "不可逆转地交出越来越多的控制权",
    "Similar to Ace's Cursed Script": "类似于Ace的诅咒脚本",
    "Slave": "奴隶",
    "This preset is a much more": "这种预设是一种更加极端的",
    "extreme submissive experience,": "顺从体验,没有给您留下太多的",
    "not leaving much control over the": "设置和权限控制,",
    "settings and permissions to you,": "从而使其他人能够在",
    "thus enabling others to use many": "您身上使用BCX的许多功能.",
    "of BCX's features on you. Owners": "如果支配者想要,",
    "can even unblock the most extreme": "他们甚至可以解除",
    "settings, if they desire so.": "最极端设置的封锁.",
    "BCX: First time init finalized": "BCX: 首次初始化完成",
    "This is the latest version": "这是最新版本",
    "View changelog": "查看更新日志",
    "Enable typing indicator": "启用输入指示器",
    "Show BCX icons above characters in chatroom": "在聊天室中显示BCX图标在角色上方",
    "Show your BCX Supporter Heart to all BCX users": "向所有BCX用户展示你的BCX支持者称号",
    "Cheat: Give yourself the mistress padlock and its key": "作弊: 给自己女主人挂锁和钥匙",
    "Cheat: Give yourself the pandora padlock and its key": "作弊: 给自己潘多拉挂锁和钥匙",
    "- Permanent deletion of ALL Bondage Club Extended data -": "- 永久删除所有 Bondage Club 扩展数据 -",
    "Use the following text to auto fill the chat room search field:": "使用以下文字自动填充聊天室搜索字段:",
    "Hide BC's typing & wardrobe icon on users showing BCX one": "在显示BCX 的输入和衣柜图标的用户上隐藏BC的",
    "Cheat: Prevent random NPC events (kidnappings, ransoms, asylum, club slaves)":
        "作弊: 防止随机NPC事件(绑架,赎金,收容所,俱乐部奴隶)",
    "Enable status indicator showing when you are in any player's BCX menu, biography, or wardrobe":
        "当你在任何玩家的BCX菜单、简介或衣柜时,启用状态指示器",
    "If you confirm, all BCX data (including settings, curses, logs, ...) will be permanently deleted!":
        "如果您确认,所有BCX数据(包括设置,诅咒,日志,…)将被永久删除!",
    "you confirm, all BCX data (including settings, curses, logs, ...) will be permanently deleted!":
        "您确认后,所有BCX数据(包括设置,诅咒,日志,…)将被永久删除!",
    "As part of the deletion process, the window will reload, logging you out of your account.":
        "作为删除过程的一部分,窗口将重新加载,使您退出您的帐户",
    "You will be able to use BCX again, but none of your current data will be coming back!":
        "您将能够再次使用BCX,但您当前的任何数据都不会存在!",
    "Cheat: Prevent loosing Mistress status when reputation falls below 50 dominance":
        "作弊: 在声望低于50支配力时防止失去女主人地位",
    "Use the extended wardrobe importer as default": "使用扩展的衣橱导入器作为默认设置",
    "This action cannot be undone!": "此操作无法撤销!",
    "Authority module permissions": "权限模块权限",
    "Hierarchy of roles:": "角色权限层次结构:",
    "Actual character name": "实际角色名字",
    "Lowest permitted role": "最低允许角色",
    "Enforce speaking it?": "强制说出?",
    "Export compressed": "导出压缩",
    "Member Number:": "角色编号:",
    "Behaviour Log": "行为日志",
    "Custom name": "自定义名字",
    "- Warning -": "- 警告 -",
    "Deleting...": "删除中…",
    "is permitted": "允许",
    "New name:": "新名字:",
    "Commands": "指令",
    "Filter:": "筛选:",
    "Attach": "附加",
    "note:": "记录:",
    "Curses": "诅咒",
    "Body": "身体",
    "when": "当",
    "Praise": "表扬",
    "Only note": "仅注释",
    "Scold": "责备",
    "Name": "名字",
    "Note": "说明",
    "room": "房间",
    "Rules": "规则",
    "Items": "物品",
    "Normal": "普通",
    "Limited": "限制",
    "Blocked": "屏蔽",
    "Clothing": "服装",
    "Relationships": "关系",
    "room named": "房间名字",
    "Filter name:": "筛选名称:",
    "Member number": "角色编号",
    "room with role": "房间存在",
    "Timer disabled": "禁用定时器",
    "room with member": "房间存在",
    "Enforce this rule": "执行此规则",
    "Rule trigger conditions:": "规则触发条件:",
    "Please select a member.": "请选择一名角色.",
    "Curse trigger conditions:": "诅咒触发条件:",
    "Timer disabled by default": "定时器默认禁用",
    "Remove the item when the curse": "移除诅咒时同时移除物品",
    "Set to global rules configuration": "设置为全局规则配置",
    "Set to global curses configuration": "设置为全局诅咒配置",
    "Example: which rope tie is used": "示例: 哪一种绳索绑法",
    "Also curse the item's configuration": "同时对物品的配置施加诅咒",
    "This rule is active and can trigger": "该规则处于激活状态,可触发",
    "This curse is active and can trigger": "这个诅咒是有效的,可以触发",
    "- View / Edit the 'Miscellaneous' curse -": "- 查看/编辑 '杂项'诅咒 -",
    "triggering - does not remove locked items": "触发 - 不会移除锁定的物品",
    "becomes inactive, removed, or is no longer": "变得不活跃,被移除,或不再存在",
    "- View / Edit the global curses configuration -": "- 查看/编辑 全局诅咒配置 -",
    "- View / Edit the 'Ready to be summoned' rule -": "- 查看/编辑 '传唤准备'规则 -",
    "Note: Settings are applied to new curses and all existing ones set to the global config.":
        "注意: 设置应用于新的诅咒和所有现有的设置到全局配置",
    '- Rules: Description of the rule: "Forbid using remotes on others"-':
        '- 规则: 规则的描述: "禁止在其他人身上使用遥控器" -',
    '- Rules: Description of the rule: "Forbid using remotes on self"-':
        '- 规则: 规则的描述: "禁止在自己身上上使用遥控器" -',
    '- Rules: Description of the rule: "Forbid using keys on others"-':
        '- 规则: 规则的描述: "禁止在其他人身上使用钥匙" -',
    '- Rules: Description of the rule: "Forbid using keys on self"-': '- 规则: 规则的描述: "禁止在自己身上使用钥匙" -',
    "- View / Edit the 'Forbid using remotes on others' rule -": "- 查看/编辑 '禁止在其他人身上使用遥控器' 规则 -",
    "- View / Edit the 'Forbid using remotes on self' rule -": "- 查看/编辑 '禁止在自己身上上使用遥控器' 规则 -",
    "- View / Edit the 'Forbid using keys on others' rule -": "- 查看/编辑 '禁止在其他人身上使用钥匙' 规则 -",
    "- View / Edit the 'Forbid using keys on self' rule -": "- 查看/编辑 '禁止在自己身上使用钥匙' 规则 -",
    '- Rules: Description of the rule: "Forbid tying up others"-': '- 规则: 规则的描述: "禁止捆绑他人" -',
    '- Rules: Description of the rule: "Prevent blacklisting"-': '- 规则: 规则的描述: "禁止增加黑名单" -',
    '- Rules: Description of the rule: "Forbid freeing self"-': '- 规则: 规则的描述: "禁止释放自己" -',
    "- View / Edit the 'Forbid using locks on self' rule -": "- 查看/编辑 '禁止对自己使用锁' 规则 -",
    "- View / Edit the 'Restrict allowed body poses' rule -": "- 查看/编辑 '限制身体姿势' 规则 -",
    "- View / Edit the 'Forbid tying up others' rule -": "- 查看/编辑 '禁止捆绑他人' 规则 -",
    "- View / Edit the 'Prevent blacklisting' rule -": "- 查看/编辑 '禁止增加黑名单' 规则 -",
    "- View / Edit the 'Forbid freeing self' rule -": "- 查看/编辑 '禁止释放自己' 规则 -",
    "- Global: Enable/Disable BCX's modules -": "- 全局: 启用/禁用BCX的模块 -",
    "- View / Edit the 'Restrict entering rooms' rule -": "- 查看/编辑 '限制进入房间' 规则 -",
    "- View / Edit the 'Prevent leaving the room' rule -": "- 查看/编辑 '阻止离开房间' 规则 -",
    "- View / Edit the 'Forbid creating new rooms' rule -": "- 查看/编辑 '禁止创建新房间' 规则 -",
    "- View / Edit the 'Forbid picking locks on self' rule -": "- 查看/编辑 '禁止撬自己的锁' 规则 -",
    "- View / Edit the 'Forbid wardrobe use on self' rule -": "- 查看/编辑 '禁止自己使用衣柜' 规则 -",
    "- View / Edit the 'Forbid picking locks on others' rule -": "- 查看/编辑 '禁止撬别人的锁' 规则 -",
    "- View / Edit the 'Forbid using locks on others' rule -": "- 查看/编辑 '禁止对其他人使用锁' 规则 -",
    '- Rules: Description of the rule: "Restrict entering rooms"-': '- 规则: 规则的描述: "限制进入房间" -',
    '- Rules: Description of the rule: "Prevent leaving the room"-': '- 规则: 规则的描述: "阻止离开房间" -',
    "- View / Edit the 'Forbid wardrobe use on others' rule -": "- 查看/编辑 '禁止在别人身上使用衣柜' 规则 -",
    '- Rules: Description of the rule: "Forbid creating new rooms"-': '- 规则: 规则的描述: "禁止创建新房间" -',
    '- Rules: Description of the rule: "Restrict allowed body poses"-': '- 规则: 规则的描述: "限制身体姿势" -',
    '- Rules: Description of the rule: "Forbid using locks on self"-': '- 规则: 规则的描述: "禁止对自己使用锁" -',
    '- Rules: Description of the rule: "Forbid picking locks on self"-': '- 规则: 规则的描述: "禁止撬自己的锁" -',
    '- Rules: Description of the rule: "Forbid wardrobe use on self"-': '- 规则: 规则的描述: "禁止自己使用衣柜" -',
    '- Rules: Description of the rule: "Forbid picking locks on others"-': '- 规则: 规则的描述: "禁止撬别人的锁" -',
    '- Rules: Description of the rule: "Forbid using locks on others"-': '- 规则: 规则的描述: "禁止对其他人使用锁" -',
    '- Rules: Description of the rule: "Forbid wardrobe use on others"-':
        '- 规则: 规则的描述: "禁止在别人身上使用衣柜" -',
    "Warning: Disabling a module will reset all its settings and stored data!":
        "警告: 禁用模块将重置其所有设置和存储的数据!",
    '- Rules: Description of the rule: "Forbid the antiblind command"-': '- 规则: 规则的描述: "禁止使用防盲指令" -',
    '- Rules: Description of the rule: "Prevent usage of all activities"-':
        '- 规则: 规则的描述: "禁止使用所有交互活动" -',
    '- Rules: Description of the rule: "Forbid mainhall maid services"-': '- 规则: 规则的描述: "禁止大厅女仆服务" -',
    '- Rules: Description of the rule: "Forbid changing difficulty"-': '- 规则: 规则的描述: "禁止改变难度" -',
    '- Rules: Description of the rule: "Prevent whitelisting"-': '- 规则: 规则的描述: "禁止增加白名单" -',
    "- View / Edit the 'Prevent usage of all activities' rule -": "- 查看/编辑 '禁止使用所有交互活动' 规则 -",
    "- View / Edit the 'Forbid mainhall maid services' rule -": "- 查看/编辑 '禁止大厅女仆服务' 规则 -",
    "- View / Edit the 'Forbid changing difficulty' rule -": "- 查看/编辑 '禁止改变难度' 规则 -",
    "- View / Edit the 'Prevent whitelisting' rule -": "- 查看/编辑 '禁止增加白名单' 规则 -",
    "- View / Edit the 'Forbid the antiblind command' rule -": "- 查看/编辑 '禁止使用防盲指令' 规则 -",
    '- Rules: Description of the rule: "Forbid the action command"-': '- 规则: 规则的描述: "禁止动作指令" -',
    "- View / Edit the 'Forbid the action command' rule -": "- 查看/编辑 '禁止动作指令' 规则 -",
    '- Rules: Description of the rule: "Prevent using BCX permissions"-': '- 规则: 规则的描述: "禁止使用BCX权限" -',
    "- View / Edit the 'Prevent using BCX permissions' rule -": "- 查看/编辑 '禁止使用BCX权限' 规则 -",
    '- Rules: Description of the rule: "Forbid looking at room admin UI"-':
        '- 规则: 规则的描述: "禁止查看房间管理界面" -',
    "- View / Edit the 'Forbid looking at room admin UI' rule -": "- 查看/编辑 '禁止查看房间管理界面' 规则 -",
    '- Rules: Description of the rule: "Forbid using GGTS"-': '- 规则: 规则的描述: "禁止使用GGTS" -',
    "- View / Edit the 'Forbid using GGTS' rule -": "- 查看/编辑 '禁止使用GGTS' 规则 -",
    '- Rules: Description of the rule: "Prevent working as club slave"-': '- 规则: 规则的描述: "禁止成为俱乐部奴隶" -',
    "- View / Edit the 'Prevent working as club slave' rule -": "- 查看/编辑 '禁止成为俱乐部奴隶' 规则 -",
    '- Rules: Description of the rule: "Prevent using items of others"-': '- 规则: 规则的描述: "禁止使用其他人物品" -',
    "- View / Edit the 'Prevent using items of others' rule -": "- 查看/编辑 '禁止使用其他人物品' 规则 -",
    '- Rules: Description of the rule: "Prevent changing own emoticon"-':
        '- 规则: 规则的描述: "禁止更改自己的状态符号" -',
    "- View / Edit the 'Prevent changing own emoticon' rule -": "- 查看/编辑 '禁止更改自己的状态符号' 规则 -",
    '- Rules: Description of the rule: "Force-hide UI elements"-': '- 规则: 规则的描述: "强制隐藏UI元素" -',
    "- View / Edit the 'Force-hide UI elements' rule -": "- 查看/编辑 '强制隐藏UI元素' 规则 -",
    '- Rules: Description of the rule: "Sensory deprivation: Sound"-': '- 规则: 规则的描述: "感觉剥夺: 听觉" -',
    "- View / Edit the 'Sensory deprivation: Sound' rule -": "- 查看/编辑 '感觉剥夺: 听觉' 规则 -",
    '- Rules: Description of the rule: "Hearing whitelist"-': '- 规则: 规则的描述: "听觉白名单" -',
    "- View / Edit the 'Hearing whitelist' rule -": "- 查看/编辑 '听觉白名单' 规则 -",
    '- Rules: Description of the rule: "Sensory deprivation: Sight"-': '- 规则: 规则的描述: "感觉剥夺:视觉" -',
    "- View / Edit the 'Sensory deprivation: Sight' rule -": "- 查看/编辑 '感觉剥夺:视觉' 规则 -",
    '- Rules: Description of the rule: "Seeing whitelist"-': '- 规则: 规则的描述: "视觉白名单" -',
    "- View / Edit the 'Seeing whitelist' rule -": "- 查看/编辑 '视觉白名单' 规则 -",
    '- Rules: Description of the rule: "Fully blind when eyes are closed"-':
        '- 规则: 规则的描述: "闭上眼睛时完全失明" -',
    "- View / Edit the 'Fully blind when eyes are closed' rule -": "- 查看/编辑 '闭上眼睛时完全失明' 规则 -",
    '- Rules: Description of the rule: "Field of vision for eyes"-': '- 规则: 规则的描述: "眼睛视野" -',
    "- View / Edit the 'Field of vision for eyes' rule -": "- 查看/编辑 '眼睛视野' 规则 -",
    '- Rules: Description of the rule: "Fully blind when blindfolded"-': '- 规则: 规则的描述: "蒙眼时完全看不见" -',
    "- View / Edit the 'Fully blind when blindfolded' rule -": "- 查看/编辑 '蒙眼时完全看不见' 规则 -",
    '- Rules: Description of the rule: "Always leave rooms slowly"-': '- 规则: 规则的描述: "总是缓慢离开房间" -',
    "- View / Edit the 'Always leave rooms slowly' rule -": "- 查看/编辑 '总是缓慢离开房间' 规则 -",
    '- Rules: Description of the rule: "Set slowed leave time"-': '- 规则: 规则的描述: "设置缓慢离开时间" -',
    "- View / Edit the 'Set slowed leave time' rule -": "- 查看/编辑 '设置缓慢离开时间' 规则 -",
    '- Rules: Description of the rule: "Control ability to orgasm"-': '- 规则: 规则的描述: "控制高潮" -',
    "- View / Edit the 'Control ability to orgasm' rule -": "- 查看/编辑 '控制高潮' 规则 -",
    '- Rules: Description of the rule: "Secret orgasm progress"-': '- 规则: 规则的描述: "隐藏高潮进度" -',
    "- View / Edit the 'Secret orgasm progress' rule -": "- 查看/编辑 '隐藏高潮进度' 规则 -",
    '- Rules: Description of the rule: "Room admin transfer"-': '- 规则: 规则的描述: "设置房间管理" -',
    "- View / Edit the 'Room admin transfer' rule -": "- 查看/编辑 '设置房间管理' 规则 -",
    '- Rules: Description of the rule: "Limit bound admin power"-': '- 规则: 规则的描述: "限制被束缚时管理员的权限" -',
    "- View / Edit the 'Limit bound admin power' rule -": "- 查看/编辑 '限制被束缚时管理员的权限' 规则 -",
    '- Rules: Description of the rule: "Control profile online description"-': '- 规则: 规则的描述: "控制在线描述" -',
    "- View / Edit the 'Control profile online description' rule -": "- 查看/编辑 '控制在线描述' 规则 -",
    '- Rules: Description of the rule: "Control playername"-': '- 规则: 规则的描述: "控制昵称" -',
    "- View / Edit the 'Control playername' rule -": "- 查看/编辑 '控制昵称' 规则 -",
    '- Rules: Description of the rule: "Always carry a suitcase"-': '- 规则: 规则的描述: "总是携带手提箱" -',
    "- View / Edit the 'Always carry a suitcase' rule -": "- 查看/编辑 '总是携带手提箱' 规则 -",
    '- Rules: Description of the rule: "Restrict being leashed by others"-': '- 规则: 规则的描述: "限制被别人牵引" -',
    "- View / Edit the 'Restrict being leashed by others' rule -": "- 查看/编辑 '限制被别人牵引' 规则 -",
    '- Rules: Description of the rule: "Hide online friends if blind"-': '- 规则: 规则的描述: "失明时隐藏好友列表" -',
    "- View / Edit the 'Hide online friends if blind' rule -": "- 查看/编辑 '失明时隐藏好友列表' 规则 -",
    '- Rules: Description of the rule: "Ready to be summoned"-': '- 规则: 规则的描述: "准备被召唤" -',
    '- Rules: Description of the rule: "Allow changing the whole appearance"-':
        '- 规则: 规则的描述: "允许改变整体外观" -',
    "- View / Edit the 'Allow changing the whole appearance' rule -": "- 查看/编辑 '允许改变整体外观' 规则 -",
    "- Rules: Description of the rule: \"Force 'Item permission'\"-": "- 规则: 规则的描述: \"强制 '物品权限'\" -",
    "- View / Edit the 'Force 'Item permission'' rule -": "- 查看/编辑 '强制 '物品权限'' 规则 -",
    "- Rules: Description of the rule: \"Force 'Locks on you can't be picked'\"-":
        "- 规则: 规则的描述: \"强制 '锁在你身上无法被撬开'\" -",
    "- View / Edit the 'Force 'Locks on you can't be picked'' rule -":
        "- 查看/编辑 '强制 '锁在你身上无法被撬开'' 规则 -",
    "- Rules: Description of the rule: \"Force 'Cannot enter single-player rooms when restrained'\"-":
        "- 规则: 规则的描述: \"强制 '当被束缚时不能进入单人房间'\" -",
    "- View / Edit the 'Force 'Cannot enter single-player rooms when restrained'' rule -":
        "- 查看/编辑 '强制 '当被束缚时不能进入单人房间'' 规则 -",
    "- Rules: Description of the rule: \"Force 'Allow safeword use'\"-":
        "- 规则: 规则的描述: \"强制 '允许使用安全词'\" -",
    "- View / Edit the 'Force 'Allow safeword use'' rule -": "- 查看/编辑 '强制 '允许使用安全词'' 规则 -",
    "- Rules: Description of the rule: \"Force 'Arousal meter'\"-": "- 规则: 规则的描述: \"强制 '高潮条'\" -",
    "- View / Edit the 'Force 'Arousal meter'' rule -": "- 查看/编辑 '强制 '高潮条'' 规则 -",
    "- Rules: Description of the rule: \"Force 'Block advanced vibrator modes'\"-":
        "- 规则: 规则的描述: \"强制 '屏蔽高级震动器模式'\" -",
    "- View / Edit the 'Force 'Block advanced vibrator modes'' rule -":
        "- 查看/编辑 '强制 '屏蔽高级震动器模式'' 规则 -",
    "- Rules: Description of the rule: \"Force 'Arousal speech stuttering'\"-":
        "- 规则: 规则的描述: \"强制 '兴奋口吃'\" -",
    "- View / Edit the 'Force 'Arousal speech stuttering'' rule -": "- 查看/编辑 '强制 '兴奋口吃'' 规则 -",
    "- Rules: Description of the rule: \"Force 'Show AFK bubble'\"-": "- 规则: 规则的描述: \"强制 '显示AFK气泡'\" -",
    "- View / Edit the 'Force 'Show AFK bubble'' rule -": "- 查看/编辑 '强制 '显示AFK气泡'' 规则 -",
    "- Rules: Description of the rule: \"Force 'Allow others to alter your whole appearance'\"-":
        "- 规则: 规则的描述: \"强制 '允许别人改变你的整体外观'\" -",
    "- View / Edit the 'Force 'Allow others to alter your whole appearance'' rule -":
        "- 查看/编辑 '强制 '允许别人改变你的整体外观'' 规则 -",
    "- Rules: Description of the rule: \"Force 'Prevent others from changing cosplay items'\"-":
        "- 规则: 规则的描述: \"强制 '禁止别人更换你的角色扮演道具'\" -",
    "- View / Edit the 'Force 'Prevent others from changing cosplay items'' rule -":
        "- 查看/编辑 '强制 '禁止别人更换你的角色扮演道具'' 规则 -",
    "- Rules: Description of the rule: \"Force 'Sensory deprivation setting'\"-":
        "- 规则: 规则的描述: \"强制 '感官剥夺设置'\" -",
    "- View / Edit the 'Force 'Sensory deprivation setting'' rule -": "- 查看/编辑 '强制 '感官剥夺设置'' 规则 -",
    "- Rules: Description of the rule: \"Force 'Hide non-adjacent players while partially blind'\"-":
        "- 规则: 规则的描述: \"强制 '在部分失明时隐藏非相邻玩家'\" -",
    "- View / Edit the 'Force 'Hide non-adjacent players while partially blind'' rule -":
        "- 查看/编辑 '强制 '在部分失明时隐藏非相邻玩家'' 规则 -",
    "- Rules: Description of the rule: \"Force 'Garble chatroom names and descriptions while blind'\"-":
        "- 规则: 规则的描述: \"强制 '失明时混淆聊天室名称和描述'\" -",
    "- View / Edit the 'Force 'Garble chatroom names and descriptions while blind'' rule -":
        "- 查看/编辑 '强制 '失明时混淆聊天室名称和描述'' 规则 -",
    "- Rules: Description of the rule: \"Force 'Keep all restraints when relogging'\"-":
        "- 规则: 规则的描述: \"强制 '重新登录时保存所有拘束和道具'\" -",
    "- View / Edit the 'Force 'Keep all restraints when relogging'' rule -":
        "- 查看/编辑 '强制 '重新登录时保存所有拘束和道具'' 规则 -",
    "- Rules: Description of the rule: \"Force 'Players can drag you to rooms when leashed'\"-":
        "- 规则: 规则的描述: \"强制 '当被牵住时,玩家可以将你拖到房间'\" -",
    "- View / Edit the 'Force 'Players can drag you to rooms when leashed'' rule -":
        "- 查看/编辑 '强制 '当被牵住时,玩家可以将你拖到房间'' 规则 -",
    "- Rules: Description of the rule: \"Force 'Return to chatrooms on relog'\"-":
        "- 规则: 规则的描述: \"强制 '重新登录时返回聊天室'\" -",
    "- View / Edit the 'Force 'Return to chatrooms on relog'' rule -":
        "- 查看/编辑 '强制 '重新登录时返回聊天室'' 规则 -",
    "- Rules: Description of the rule: \"Force 'Events while plugged or vibed'\"-":
        "- 规则: 规则的描述: \"强制 '插着或振动时发生事件'\" -",
    "- View / Edit the 'Force 'Events while plugged or vibed'' rule -":
        "- 查看/编辑 '强制 '插着或振动时发生事件'' 规则 -",
    "- Rules: Description of the rule: \"Force 'Allow item tint effects'\"-":
        "- 规则: 规则的描述: \"强制 '允许物品染色'\" -",
    "- View / Edit the 'Force 'Allow item tint effects'' rule -": "- 查看/编辑 '强制 '允许物品染色'' 规则 -",
    "- Rules: Description of the rule: \"Force 'Allow item blur effects'\"-":
        "- 规则: 规则的描述: \"强制 '允许物品模糊'\" -",
    "- View / Edit the 'Force 'Allow item blur effects'' rule -": "- 查看/编辑 '强制 '允许物品模糊'' 规则 -",
    "- Rules: Description of the rule: \"Force 'Flip room vertically when upside-down'\"-":
        "- 规则: 规则的描述: \"强制 '倒立时垂直翻转房间'\" -",
    "- View / Edit the 'Force 'Flip room vertically when upside-down'' rule -":
        "- 查看/编辑 '强制 '倒立时垂直翻转房间'' 规则 -",
    "- Rules: Description of the rule: \"Force 'Prevent random NPC events'\"-":
        "- 规则: 规则的描述: \"强制 '阻止随机NPC事件'\" -",
    "- View / Edit the 'Force 'Prevent random NPC events'' rule -": "- 查看/编辑 '强制 '阻止随机NPC事件'' 规则 -",
    '- Rules: Description of the rule: "Forbid club owner changes"-': '- 规则: 规则的描述: "禁止更换主人" -',
    "- View / Edit the 'Forbid club owner changes' rule -": "- 查看/编辑 '禁止更换主人' 规则 -",
    '- Rules: Description of the rule: "Forbid getting new lovers"-': '- 规则: 规则的描述: "禁止交新的恋人" -',
    "- View / Edit the 'Forbid getting new lovers' rule -": "- 查看/编辑 '禁止交新的恋人' 规则 -",
    '- Rules: Description of the rule: "Forbid breaking up with lovers"-': '- 规则: 规则的描述: "禁止与恋人分手" -',
    "- View / Edit the 'Forbid breaking up with lovers' rule -": "- 查看/编辑 '禁止与恋人分手' 规则 -",
    '- Rules: Description of the rule: "Forbid taking new submissives"-': '- 规则: 规则的描述: "禁止接收新的顺服者" -',
    "- View / Edit the 'Forbid taking new submissives' rule -": "- 查看/编辑 '禁止接收新的顺服者' 规则 -",
    '- Rules: Description of the rule: "Forbid disowning submissives"-': '- 规则: 规则的描述: "禁止放弃顺从者" -',
    "- View / Edit the 'Forbid disowning submissives' rule -": "- 查看/编辑 '禁止放弃顺从者' 规则 -",
    '- Rules: Description of the rule: "Allow specific sounds only"-': '- 规则: 规则的描述: "仅允许特定声音" -',
    "- View / Edit the 'Allow specific sounds only' rule -": "- 查看/编辑 '仅允许特定声音' 规则 -",
    '- Rules: Description of the rule: "Garble whispers while gagged"-': '- 规则: 规则的描述: "嘴巴被堵住时混淆私语" -',
    "- View / Edit the 'Garble whispers while gagged' rule -": "- 查看/编辑 '嘴巴被堵住时混淆私语' 规则 -",
    '- Rules: Description of the rule: "Block OOC chat while gagged"-':
        '- 规则: 规则的描述: "嘴巴被堵住时阻止OOC聊天" -',
    "- View / Edit the 'Block OOC chat while gagged' rule -": "- 查看/编辑 '嘴巴被堵住时阻止OOC聊天' 规则 -",
    '- Rules: Description of the rule: "Block OOC chat"-': '- 规则: 规则的描述: "阻止OOC聊天" -',
    "- View / Edit the 'Block OOC chat' rule -": "- 查看/编辑 '阻止OOC聊天' 规则 -",
    '- Rules: Description of the rule: "Doll talk"-': '- 规则: 规则的描述: "玩偶说话" -',
    "- View / Edit the 'Doll talk' rule -": "- 查看/编辑 '玩偶说话' 规则 -",
    '- Rules: Description of the rule: "Forbid saying certain words in chat"-':
        '- 规则: 规则的描述: "禁止在聊天中说某些词语" -',
    "- View / Edit the 'Forbid saying certain words in chat' rule -": "- 查看/编辑 '禁止在聊天中说某些词语' 规则 -",
    '- Rules: Description of the rule: "Forbid saying certain words in emotes"-':
        '- 规则: 规则的描述: "禁止在表情中说某些词语" -',
    "- View / Edit the 'Forbid saying certain words in emotes' rule -": "- 查看/编辑 '禁止在表情中说某些词语' 规则 -",
    '- Rules: Description of the rule: "Forbid talking openly"-': '- 规则: 规则的描述: "禁止公开交谈" -',
    "- View / Edit the 'Forbid talking openly' rule -": "- 查看/编辑 '禁止公开交谈' 规则 -",
    '- Rules: Description of the rule: "Limit talking openly"-': '- 规则: 规则的描述: "限制公开交谈" -',
    "- View / Edit the 'Limit talking openly' rule -": "- 查看/编辑 '限制公开交谈' 规则 -",
    '- Rules: Description of the rule: "Forbid using emotes"-': '- 规则: 规则的描述: "禁止使用表情" -',
    "- View / Edit the 'Forbid using emotes' rule -": "- 查看/编辑 '禁止使用表情' 规则 -",
    '- Rules: Description of the rule: "Limit using emotes"-': '- 规则: 规则的描述: "限制使用表情" -',
    "- View / Edit the 'Limit using emotes' rule -": "- 查看/编辑 '限制使用表情' 规则 -",
    '- Rules: Description of the rule: "Restrict sending whispers"-': '- 规则: 规则的描述: "限制发送私语" -',
    "- View / Edit the 'Restrict sending whispers' rule -": "- 查看/编辑 '限制发送私语' 规则 -",
    '- Rules: Description of the rule: "Restrict receiving whispers"-': '- 规则: 规则的描述: "限制接收私语" -',
    "- View / Edit the 'Restrict receiving whispers' rule -": "- 查看/编辑 '限制接收私语' 规则 -",
    '- Rules: Description of the rule: "Restrict sending beep messages"-': '- 规则: 规则的描述: "限制发送蜂鸣消息" -',
    "- View / Edit the 'Restrict sending beep messages' rule -": "- 查看/编辑 '限制发送蜂鸣消息' 规则 -",
    '- Rules: Description of the rule: "Restrict receiving beeps"-': '- 规则: 规则的描述: "限制接收蜂鸣" -',
    "- View / Edit the 'Restrict receiving beeps' rule -": "- 查看/编辑 '限制接收蜂鸣' 规则 -",
    '- Rules: Description of the rule: "Order to greet club"-': '- 规则: 规则的描述: "登录时自动发蜂鸣消息" -',
    "- View / Edit the 'Order to greet club' rule -": "- 查看/编辑 '登录时自动发蜂鸣消息' 规则 -",
    '- Rules: Description of the rule: "Forbid the antigarble option"-': '- 规则: 规则的描述: "禁止反语言混淆选项" -',
    "- View / Edit the 'Forbid the antigarble option' rule -": "- 查看/编辑 '禁止反语言混淆选项' 规则 -",
    '- Rules: Description of the rule: "Force to retype"-': '- 规则: 规则的描述: "强制重新输入" -',
    "- View / Edit the 'Force to retype' rule -": "- 查看/编辑 '强制重新输入' 规则 -",
    '- Rules: Description of the rule: "Order to greet room"-':
        '- 规则: 规则的描述: "进房间时自动发出设置好的问候语" -',
    "- View / Edit the 'Order to greet room' rule -": "- 查看/编辑 '进房间时自动发出设置好的问候语' 规则 -",
    '- Rules: Description of the rule: "Greet new guests"-': '- 规则: 规则的描述: "问候新客人" -',
    "- View / Edit the 'Greet new guests' rule -": "- 查看/编辑 '问候新客人' 规则 -",
    '- Rules: Description of the rule: "Enforce faltering speech"-': '- 规则: 规则的描述: "强制断句" -',
    "- View / Edit the 'Enforce faltering speech' rule -": "- 查看/编辑 '强制断句' 规则 -",
    '- Rules: Description of the rule: "Establish mandatory words"-': '- 规则: 规则的描述: "建立强制性词汇" -',
    "- View / Edit the 'Establish mandatory words' rule -": "- 查看/编辑 '建立强制性词汇' 规则 -",
    '- Rules: Description of the rule: "Establish mandatory words in emotes"-':
        '- 规则: 规则的描述: "在表情中建立强制性词汇" -',
    "- View / Edit the 'Establish mandatory words in emotes' rule -": "- 查看/编辑 '在表情中建立强制性词汇' 规则 -",
    '- Rules: Description of the rule: "Partial hearing"-': '- 规则: 规则的描述: "部分听觉" -',
    "- View / Edit the 'Partial hearing' rule -": "- 查看/编辑 '部分听觉' 规则 -",
    '- Rules: Description of the rule: "Force garbled speech"-': '- 规则: 规则的描述: "强制口吃" -',
    "- View / Edit the 'Force garbled speech' rule -": "- 查看/编辑 '强制口吃' 规则 -",
    '- Rules: Description of the rule: "Forbid going afk"-': '- 规则: 规则的描述: "禁止afk" -',
    "- View / Edit the 'Forbid going afk' rule -": "- 查看/编辑 '禁止afk' 规则 -",
    '- Rules: Description of the rule: "Track rule effect time"-': '- 规则: 规则的描述: "追踪规则触发的时间" -',
    "- View / Edit the 'Track rule effect time' rule -": "- 查看/编辑 '追踪规则触发的时间' 规则 -",
    '- Rules: Description of the rule: "Listen to my voice"-': '- 规则: 规则的描述: "听见我的声音" -',
    "- View / Edit the 'Listen to my voice' rule -": "- 查看/编辑 '听见我的声音' 规则 -",
    '- Rules: Description of the rule: "Log money changes"-': '- 规则: 规则的描述: "记录货币变化" -',
    "- View / Edit the 'Log money changes' rule -": "- 查看/编辑 '记录货币变化' 规则 -",
    '- Rules: Description of the rule: "Track BCX activation"-': '- 规则: 规则的描述: "追踪BCX激活" -',
    "- View / Edit the 'Track BCX activation' rule -": "- 查看/编辑 '追踪BCX激活' 规则 -",
    '- Commands: Description of the command: "Eyes" -': '- 指令: 指令的描述: "眼睛" -',
    '- Commands: Description of the command: "Mouth" -': '- 指令: 指令的描述: "嘴巴" -',
    '- Commands: Description of the command: "Arms" -': '- 指令: 指令的描述: "手臂" -',
    '- Commands: Description of the command: "Legs" -': '- 指令: 指令的描述: "腿" -',
    '- Commands: Description of the command: "Allfours" -': '- 指令: 指令的描述: "四肢着地" -',
    '- Commands: Description of the command: "Go and wait" -': '- 指令: 指令的描述: "去等待" -',
    '- Commands: Description of the command: "Send to cell" -': '- 指令: 指令的描述: "送进监狱" -',
    '- Commands: Description of the command: "Send to asylum" -': '- 指令: 指令的描述: "送进收容所" -',
    '- Commands: Description of the command: "Deposit all keys" -': '- 指令: 指令的描述: "没收所有钥匙" -',
    '- Commands: Description of the command: "Show remaining time" -': '- 指令: 指令的描述: "显示剩余时间" -',
    '- Commands: Description of the command: "Send to serve drinks" -': '- 指令: 指令的描述: "送去招待饮料" -',
    '- Commands: Description of the command: "Manipulate the arousal meter" -': '- 指令: 指令的描述: "操纵高潮条" -',
    '- Commands: Description of the command: "Emoticon" -': '- 指令: 指令的描述: "表情符号" -',
    '- Commands: Description of the command: "Forced say" -': '- 指令: 指令的描述: "强制说" -',
    '- Commands: Description of the command: "Say" -': '- 指令: 指令的描述: "说" -',
    '- Commands: Description of the command: "Typing task" -': '- 指令: 指令的描述: "输入任务" -',
    '- Commands: Description of the command: "Forced typing task" -': '- 指令: 指令的描述: "强制输入任务" -',
    "Authority module permissions (continued)": "权限模块权限 (延续)",
    "Behaviour Log module permissions": "行为日志模块权限",
    "Behaviour Log module permissions (continued)": "行为日志模块权限 (延续)",
    "Curses module permissions": "诅咒模块权限",
    "Curses module permissions (continued)": "诅咒模块权限 (延续)",
    "Rules module permissions": "规则模块权限",
    "Commands module permissions": "指令模块权限",
    "Relationships module permissions": "关系模块权限",
    "Export-Import module permissions": "导出-导入 模块权限",
    "Miscellaneous module permissions": "其他模块权限",
    "Locks on you can't be picked": "你的锁是无法被撬开的",
    "Restore previous value when rule ends": "规则结束时恢复之前的值",
    "Behaviour log entry when rule is violated": "违反规则时记录到行为日志",
    "Allow item blur effects": "允许物品模糊效果",
    "Global": "全局",
    "Authority": "权限",
    "Export-Import": "导入导出",
    "Miscellaneous": "杂项",
    "For saying 'thank you' with a tip": "用于赞助支持",
    "Open changelog on GitHub": "在 GitHub 上打开更新日志",
    "Open invite to BCX Discord server": "打开 BCX Discord服务器邀请",
    "Show the BCX tutorial again": "再次显示 BCX教程",
    "Close tutorial": "关闭教程",
    "Page 1/20": "第 1 页/20",
    "Page 2/20": "第 2 页/20",
    "Page 3/20": "第 3 页/20",
    "Page 4/20": "第 4 页/20",
    "Page 5/20": "第 5 页/20",
    "Page 6/20": "第 6 页/20",
    "Page 7/20": "第 7 页/20",
    "Page 8/20": "第 8 页/20",
    "Page 9/20": "第 9 页/20",
    "Page 10/20": "第 10 页/20",
    "Page 11/20": "第 11 页/20",
    "Page 12/20": "第 12 页/20",
    "Page 13/20": "第 13 页/20",
    "Page 14/20": "第 14 页/20",
    "Page 15/20": "第 15 页/20",
    "Page 16/20": "第 16 页/20",
    "Page 17/20": "第 17 页/20",
    "Page 18/20": "第 18 页/20",
    "Page 19/20": "第 19 页/20",
    "Page 20/20": "第 20 页/20",
    "Instant Messenger": "即时消息",
    'Your initially selected BCX preset was: "Dominant"': '你最初选择的BCX预设是: "支配者"',
    'Your initially selected BCX preset was: "Switch"': '你最初选择的BCX预设是: "转换者"',
    'Your initially selected BCX preset was: "Submissive"': '你最初选择的BCX预设是: "服从者"',
    'Your initially selected BCX preset was: "Slave"': '你最初选择的BCX预设是: "奴隶"',
    "Manage BCX modules": "管理 BCX模块",
    "Clear all BCX data": "清除所有 BCX数据",
    "Enable/Disable individual modules": "启用/禁用 单个模块",
    "Emergency reset of BCX": "紧急重置BCX",
    "Confirm": "确认",
    "Cancel": "取消",
    "BCX main menu": "BCX 主菜单",
    "Confirm (9)": "确认 (9)",
    "Confirm (8)": "确认 (8)",
    "Confirm (7)": "确认 (7)",
    "Confirm (6)": "确认 (6)",
    "Confirm (5)": "确认 (5)",
    "Confirm (4)": "确认 (4)",
    "Confirm (3)": "确认 (3)",
    "Confirm (2)": "确认 (2)",
    "Confirm (1)": "确认 (1)",
    "Confirm (0)": "确认 (0)",
    "Add as owner": "添加为所有者",
    "Add as mistress": "添加为女主人",
    "Page 1 / 0": "第 1 页 / 0",
    "Clubowner": "俱乐部主人",
    "Owner": "所有者",
    "Lover": "恋人",
    "Mistress": "女主人",
    "Whitelist": "白名单",
    "Friend": "朋友",
    "Public": "公开",
    "Configure the role-based BCX permissions": "配置基于角色的 BCX 权限",
    "Select member number from list": "从列表中选择成员编号",
    "You - either top or bottom of the hierarchy": "你 - 可以是层次结构的顶部或底部",
    "Your owner, visible on your character profile": "你的所有者,在你的角色资料中可见",
    'Any character, added to the list on the left as "Owner"': '任何角色,添加到左侧列表中作为 "所有者"',
    "Any of your lovers, visible on your character profile": "你的任何恋人,在你的角色资料中可见",
    'Any character, added to the list on the left as "Mistress"': '任何角色,添加到左侧列表中作为 "女主人"',
    "Anyone you have white-listed": "你白名单中的任何人",
    "Anyone you have friend-listed": "你好友名单中的任何人",
    "Anyone, who can use items on you": "任何可以在你身上使用物品的人",
    "Allow forbidding self access": "允许禁止自己访问",
    "Allow granting Mistress status": "允许授予女主人身份",
    "Allow granting Owner status": "允许授予所有者身份",
    "Allow granting self access": "允许授予自己访问权限",
    "Allow lowest access modification": "允许最低访问权限修改",
    "Previous screen": "上一页",
    "Allow revoking Mistress status": "允许撤销女主人身份",
    "Allow revoking Owner status": "允许撤销所有者身份",
    "Allow viewing list of owners/mistresses": "允许查看所有者/女主人列表",
    "Allow deleting log entries": "允许删除日志条目",
    "Allow to attach notes to the body": "允许附加注释到身体上",
    "Allow to configure what is logged": "允许配置日志记录的内容",
    "Allow to praise or scold": "允许表扬或责备",
    "Allow to see normal log entries": "允许查看正常的日志条目",
    "Allow to see protected log entries": "允许查看受保护的日志内容",
    "Allow changing colors of cursed objects": "允许更改被诅咒物品的颜色",
    "Allow to view who added the curse originally": "允许查看最初添加诅咒的人",
    "Allows editing the global curses configuration": "允许编辑全局诅咒配置",
    "Allows handling curses on limited object slots": "允许在限制的物体槽上处理诅咒",
    "Allows handling curses on non-limited object slots": "允许在非限制的物体槽上处理诅咒",
    "Allows to limit/block individual curse object slots": "允许限制/阻止单个诅咒对象槽",
    "Allow to view who added the rule originally": "允许查看最初添加规则的人",
    "Allows controlling limited rules": "允许控制限制的规则",
    "Allows controlling non-limited rules": "允许控制非限制的规则",
    "Allows editing the global rules configuration": "允许编辑全局规则配置",
    "Allows to limit/block specific rules": "允许限制/阻止特定规则",
    "Allows controlling limited commands": "允许控制限制的指令",
    "Allows controlling non-limited commands": "允许控制非限制的指令",
    "Allows to limit/block specific commands": "允许限制/阻止特定指令",
    "Allow changing relationship config for herself": "允许更改自己的关系配置",
    "Allow changing relationship config for others": "允许更改其他人的关系配置",
    "Allow viewing others in relationship list": "允许查看关系列表中的其他人",
    "Allow exporting BCX module configurations": "允许导出 BCX 模块配置",
    "Allow importing items using wardrobe": "允许使用衣柜导入物品",
    "Allow using the allowactivities command on this player": "允许在此玩家上使用 allowactivities 命令",
    '- Authority: Changing minimum access to permission "Allows controlling limited commands" -':
        '- 权限: 更改对权限 "允许控制限制的指令" 的最小访问权限',
    "Info: Currently set role: Owner → Newly selected role: Owner":
        "信息: 当前设置的角色: 所有者 → 新选择的角色: 所有者",
    "This player's owner, visible on their character profile": "这个玩家的所有者,可在他们的角色资料中看到",
    "This player - either top or bottom of the hierarchy": "这个玩家 - 可能是层级的顶端或底端",
    "Any lover of this player, visible on their profile": "这个玩家的任何恋人,在他们的资料中可见",
    "Anyone this player has white-listed": "任何已加入白名单的玩家",
    "Anyone this player has friend-listed": "任何已加入好友列表的玩家",
    "Anyone, who can use items on this player": "任何可以在这个玩家身上使用物品的玩家",
    "Info: Currently set role: Public → Newly selected role: Public": "信息: 当前设置的角色: 公共 → 新选择的角色: 公共",
    "Info: Currently set role: Public → Newly selected role: Friend": "信息: 当前设置的角色: 公共 → 新选择的角色: 好友",
    "Info: Currently set role: Public → Newly selected role: Whitelist":
        "信息: 当前设置的角色: 公共 → 新选择的角色: 白名单",
    "Info: Currently set role: Public → Newly selected role: Mistress":
        "信息: 当前设置的角色: 公共 → 新选择的角色: 女主人",
    "Info: Currently set role: Public → Newly selected role: Lover": "信息: 当前设置的角色: 公共 → 新选择的角色: 恋人",
    "Info: Currently set role: Public → Newly selected role: Owner":
        "信息: 当前设置的角色: 公共 → 新选择的角色: 所有者",
    "Info: Currently set role: Public → Newly selected role: Clubowner":
        "信息: 当前设置的角色: 公共 → 新选择的角色: 俱乐部主人",
    "Info: Currently set role: Friend → Newly selected role: Friend": "信息: 当前设置的角色: 好友 → 新选择的角色: 好友",
    "Info: Currently set role: Friend → Newly selected role: Public": "信息: 当前设置的角色: 好友 → 新选择的角色: 公共",
    "Info: Currently set role: Friend → Newly selected role: Whitelist":
        "信息: 当前设置的角色: 好友 → 新选择的角色: 白名单",
    "Info: Currently set role: Friend → Newly selected role: Mistress":
        "信息: 当前设置的角色: 好友 → 新选择的角色: 女主人",
    "Info: Currently set role: Friend → Newly selected role: Lover": "信息: 当前设置的角色: 好友 → 新选择的角色: 恋人",
    "Info: Currently set role: Friend → Newly selected role: Owner":
        "信息: 当前设置的角色: 好友 → 新选择的角色: 所有者",
    "Info: Currently set role: Friend → Newly selected role: Clubowner":
        "信息: 当前设置的角色: 好友 → 新选择的角色: 俱乐部主人",
    "Info: Currently set role: Whitelist → Newly selected role: Whitelist":
        "信息: 当前设置的角色: 白名单 → 新选择的角色: 白名单",
    "Info: Currently set role: Whitelist → Newly selected role: Public":
        "信息: 当前设置的角色: 白名单 → 新选择的角色: 公共",
    "Info: Currently set role: Whitelist → Newly selected role: Friend":
        "信息: 当前设置的角色: 白名单 → 新选择的角色: 好友",
    "Info: Currently set role: Whitelist → Newly selected role: Mistress":
        "信息: 当前设置的角色: 白名单 → 新选择的角色: 女主人",
    "Info: Currently set role: Whitelist → Newly selected role: Lover":
        "信息: 当前设置的角色: 白名单 → 新选择的角色: 恋人",
    "Info: Currently set role: Whitelist → Newly selected role: Owner":
        "信息: 当前设置的角色: 白名单 → 新选择的角色: 所有者",
    "Info: Currently set role: Whitelist → Newly selected role: Clubowner":
        "信息: 当前设置的角色: 白名单 → 新选择的角色: 俱乐部主人",
    "Info: Currently set role: Mistress → Newly selected role: Mistress":
        "信息: 当前设置的角色: 女主人 → 新选择的角色: 女主人",
    "Info: Currently set role: Mistress → Newly selected role: Public":
        "信息: 当前设置的角色: 女主人 → 新选择的角色: 公共",
    "Info: Currently set role: Mistress → Newly selected role: Friend":
        "信息: 当前设置的角色: 女主人 → 新选择的角色: 好友",
    "Info: Currently set role: Mistress → Newly selected role: Whitelist":
        "信息: 当前设置的角色: 女主人 → 新选择的角色: 白名单",
    "Info: Currently set role: Mistress → Newly selected role: Lover":
        "信息: 当前设置的角色: 女主人 → 新选择的角色: 恋人",
    "Info: Currently set role: Mistress → Newly selected role: Owner":
        "信息: 当前设置的角色: 女主人 → 新选择的角色: 所有者",
    "Info: Currently set role: Mistress → Newly selected role: Clubowner":
        "信息: 当前设置的角色: 女主人 → 新选择的角色: 俱乐部主人",
    "Info: Currently set role: Lover → Newly selected role: Lover": "信息: 当前设置的角色: 恋人 → 新选择的角色: 恋人",
    "Info: Currently set role: Lover → Newly selected role: Public": "信息: 当前设置的角色: 恋人 → 新选择的角色: 公共",
    "Info: Currently set role: Lover → Newly selected role: Friend": "信息: 当前设置的角色: 恋人 → 新选择的角色: 好友",
    "Info: Currently set role: Lover → Newly selected role: Whitelist":
        "信息: 当前设置的角色: 恋人 → 新选择的角色: 白名单",
    "Info: Currently set role: Lover → Newly selected role: Mistress":
        "信息: 当前设置的角色: 恋人 → 新选择的角色: 女主人",
    "Info: Currently set role: Lover → Newly selected role: Owner": "信息: 当前设置的角色: 恋人 → 新选择的角色: 所有者",
    "Info: Currently set role: Lover → Newly selected role: Clubowner":
        "信息: 当前设置的角色: 恋人 → 新选择的角色: 俱乐部主人",
    "Info: Currently set role: Clubowner → Newly selected role: Clubowner":
        "信息: 当前设置的角色: 俱乐部主人 → 新选择的角色: 俱乐部主人",
    "Info: Currently set role: Clubowner → Newly selected role: Owner":
        "信息: 当前设置的角色: 俱乐部主人 → 新选择的角色: 所有者",
    "Info: Currently set role: Clubowner → Newly selected role: Lover":
        "信息: 当前设置的角色: 俱乐部主人 → 新选择的角色: 恋人",
    "Info: Currently set role: Clubowner → Newly selected role: Mistress":
        "信息: 当前设置的角色: 俱乐部主人 → 新选择的角色: 女主人",
    "Info: Currently set role: Clubowner → Newly selected role: Whitelist":
        "信息: 当前设置的角色: 俱乐部主人 → 新选择的角色: 白名单",
    "Info: Currently set role: Clubowner → Newly selected role: Friend":
        "信息: 当前设置的角色: 俱乐部主人 → 新选择的角色: 好友",
    "Info: Currently set role: Clubowner → Newly selected role: Public":
        "信息: 当前设置的角色: 俱乐部主人 → 新选择的角色: 公共",
    "You have no permission to use this": "您没有使用此功能的权限",
    "Skip tutorial": "跳过教程",
    "<< Back to the tutorial": "<< 返回教程",
    '- Authority: Changing minimum access to permission "Allow forbidding self access" -':
        '- 权限: 更改对权限 "允许禁止自我访问" 的最小访问权限',
    '- Authority: Changing minimum access to permission "Allows editing the global curses configuration" -':
        '- 权限: 更改对权限 "允许编辑全局诅咒配置" 的最小访问权限',
    "Info: Currently set role: Owner → Newly selected role: Lover": "信息: 当前设置的角色: 所有者 → 新选择的角色: 恋人",
    "Info: Currently set role: Owner → Newly selected role: Mistress":
        "信息: 当前设置的角色: 所有者 → 新选择的角色: 女主人",
    "Info: Currently set role: Owner → Newly selected role: Whitelist":
        "信息: 当前设置的角色: 所有者 → 新选择的角色: 白名单",
    "Info: Currently set role: Owner → Newly selected role: Friend":
        "信息: 当前设置的角色: 所有者 → 新选择的角色: 好友",
    "Info: Currently set role: Owner → Newly selected role: Public":
        "信息: 当前设置的角色: 所有者 → 新选择的角色: 公共",
    "Info: Currently set role: Owner → Newly selected role: Clubowner":
        "信息: 当前设置的角色: 所有者 → 新选择的角色: 俱乐部主人",
    "The log has been cleared": "日志已被清除",
    "Configure logging": "配置日志记录",
    "Ability to see attached notes": "能够查看附加的备注",
    "Yes": "是",
    "Log changes in logging configuration": "记录日志配置的更改",
    "Protected": "受保护的",
    "Log changes in permission settings": "记录权限设置的更改",
    "Log deleted log entries": "记录删除的日志条目",
    "Log each addition, removal or change of rules": "记录每个规则的添加、移除或更改",
    "No": "否",
    "Log each application, removal or change of curses": "记录每个诅咒的应用、移除或更改",
    "Delete all log entries": "删除所有日志条目",
    "Log each change in relationships module": "记录关系模块的每次更改",
    "Log each change of commands limit": "记录命令限制的每次更改",
    "Log each single orgasm": "记录每一次的高潮",
    "Log every rule violation": "记录每一次违规",
    "Log every time a triggered curse reapplies an item": "记录每一次触发的诅咒重新应用物品",
    "Log getting or losing a BCX owner/mistress": "记录每一次增加或删除 BCX 所有者/女主人",
    "Log praising or scolding behavior": "记录赞扬或责备的行为",
    "Log which private rooms are entered": "记录进入哪些私人房间",
    "Log which public rooms are entered": "记录进入哪些公共房间",
    "Back": "返回",
    "ALL": "全部",
    "Activate all": "全部激活",
    "A. only": "仅激活",
    "Deactivate all": "全部停用",
    "D. only": "仅停用",
    "Change global rules config": "更改全局规则配置",
    "Page 1 / 1": "第1页 / 共1页",
    "Add new rule": "添加新规则",
    "Existing rules set to global rules config are also changed": "全局规则配置中的现有规则也将被更改",
    "...from the list of yet unestablished rules": "......从尚未建立的规则列表中",
    "Switch all added rules to active": "将所有已添加规则切换为激活状态",
    "Activate only global config rules": "仅激活全局配置规则",
    "Deactivate only global config rules": "仅停用全局配置规则",
    "Switch all added rules to inactive": "将所有已添加规则切换为非激活状态",
    "Forbid using remotes on others": "禁止在其他人身上使用遥控器",
    "Forbid using keys on others": "禁止在其他人身上使用钥匙",
    "Forbid picking locks on others": "禁止在其他人身上撬锁",
    "Forbid using locks on others": "禁止在其他人身上使用锁",
    "Forbid wardrobe use on others": "禁止在其他人身上使用衣柜",
    "Restrict allowed body poses": "限制允许的身体姿势",
    "Forbid creating new rooms": "禁止创建新房间",
    "Restrict entering rooms (only allow entering specific ones)": "限制进入房间(仅允许进入特定房间)",
    "Prevent leaving the room (while defined roles are inside)": "防止离开房间(当指定的角色在房间内时)",
    "Forbid tying up others (either everybody or only more dominant characters)":
        "禁止捆绑他人(可以是所有人或仅更占主导地位的角色)",
    "Prevent blacklisting (and ghosting of the defined roles)": "防止黑名单(和指定角色的幽灵化)",
    "Prevent whitelisting (of roles 'friend' or 'public')": "防止白名单('朋友'或'公共'角色)",
    "Forbid the antiblind command (BCX's .antiblind command)": "禁止反盲命令(BCX的 .antiblind 指令)",
    "Forbid changing difficulty (multiplayer difficulty preference)": "禁止更改难度(多人游戏的难度偏好)",
    "Prevent usage of all activities (any action buttons such as kissing or groping)":
        "防止使用所有活动(如亲吻或触摸等任何动作按钮)",
    "Forbid mainhall maid services (to get out of any restraints)": "禁止主厅女仆服务(以摆脱任何约束)",
    "Forbid the action command (BCX's .action/.a chat command)": "禁止行动指令(BCX的 .action/.a 聊天指令)",
    "Forbid looking at room admin UI (while blindfolded)": "禁止查看房间管理UI(戴眼罩时)",
    "Forbid using GGTS (training by GGTS is forbidden)": "禁止使用GGTS(GGTS的培训是禁止的)",
    "Prevent working as club slave (the task from the mistress room)": "防止成为俱乐部奴隶(女王室的任务)",
    "Prevent using items of others (items not bought)": "防止使用他人的物品(未购买的物品)",
    "Force-hide UI elements (e.g., icons, bars, or names)": "强制隐藏UI元素(例如图标、条形、或名称)",
    "Fully blind when eyes are closed": "闭眼时完全失明",
    "Field of vision for eyes": "眼睛的视野",
    "Fully blind when blindfolded": "戴眼罩时完全失明",
    "Always leave rooms slowly": "始终缓慢离开房间",
    "Set slowed leave time": "设置缓慢离开时间",
    "Control ability to orgasm (adjustable: only-edge, only-ruin, no-resist)":
        "控制达到性高潮的能力(可调节: 仅限边缘,仅限毁灭,无抵抗)",
    "Secret orgasm progress (unable to see the own arousal meter)": "秘密性高潮进度(无法看到自己的高潮条)",
    "Room admin transfer (give admin to defined roles)": "房间管理员转让(将管理员权限赋予指定角色)",
    "Limit bound admin power (restrict room admin powers while restrained)":
        "限制被束缚玩家的管理员权限(在被束缚时限制房间管理员权限)",
    "Always carry a suitcase (from the kidnappers league multiplayer game)": "始终携带手提箱(来自绑匪联盟多人游戏)",
    "Restrict being leashed by others": "限制被他人牵引",
    "Hide online friends if blind (also preventing beeps from the friendlist - exceptions settable)":
        "如果失明,则隐藏在线好友(同时阻止来自好友列表的提示声音 - 可设置例外)",
    "Force 'Item permission' (Existing BC setting)": "强制 '物品权限'(现有BC设置)",
    "Force 'Locks on you can't be picked' (Existing BC setting)": "强制 '无法撬开你身上的锁'(现有BC设置)",
    "Force 'Cannot enter single-player rooms when restrained' (Existing BC setting)":
        "强制 '被束缚时无法进入单人房间'(现有BC设置)",
    "Force 'Allow safeword use' (Existing BC setting)": "强制 '允许使用安全词'(现有BC设置)",
    "Force 'Arousal meter' (Existing BC setting)": "强制 '高潮条'(现有BC设置)",
    "Force 'Block advanced vibrator modes' (Existing BC setting)": "强制 '阻止高级震动器模式'(现有BC设置)",
    "Force 'Arousal speech stuttering' (Existing BC setting)": "强制 '高潮时语速失常'(现有BC设置)",
    "Force 'Show AFK bubble' (Existing BC setting)": "强制 '显示离开键盘气泡'(现有BC设置)",
    "Force 'Allow others to alter your whole appearance' (Existing BC setting)":
        "强制 '允许他人更改你的整体外观'(现有BC设置)",
    "Force 'Prevent others from changing cosplay items' (Existing BC setting)":
        "强制 '阻止他人更改角色扮演物品'(现有BC设置)",
    "Force 'Sensory deprivation setting' (Existing BC setting)": "强制 '感官剥夺设置'(现有BC设置)",
    "Force 'Hide non-adjacent players while partially blind' (Existing BC setting)":
        "强制 '在局部失明时隐藏非邻近玩家'(现有BC设置)",
    "Force 'Garble chatroom names and descriptions while blind' (Existing BC setting)":
        "强制 '局部失明时混淆聊天室名称和描述'(现有BC设置)",
    "Force 'Keep all restraints when relogging' (Existing BC setting)": "强制 '重新登录时保存所有约束'(现有BC设置)",
    "Force 'Players can drag you to rooms when leashed' (Existing BC setting)":
        "强制 '当被牵引时允许玩家将你拖到其他房间'(现有BC设置)",
    "Force 'Return to chatrooms on relog' (Existing BC setting)": "强制 '重新登录时返回聊天室'(现有BC设置)",
    "Force 'Events while plugged or vibed' (Existing BC setting)": "强制 '插入或震动时发生事件'(现有BC设置)",
    "Force 'Allow item tint effects' (Existing BC setting)": "强制 '允许物品着色效果'(现有BC设置)",
    "Force 'Allow item blur effects' (Existing BC setting)": "强制 '允许物品模糊效果'(现有BC设置)",
    "Force 'Flip room vertically when upside-down' (Existing BC setting)": "强制 '倒置时垂直翻转房间'(现有BC设置)",
    "Force 'Prevent random NPC events' (from BCX's Misc module)": "强制 '阻止随机NPC事件'(来自BCX的Misc模块)",
    "Forbid club owner changes (getting or leaving owner)": "禁止更改俱乐部主人(获得或离开主人)",
    "Forbid getting new lovers": "禁止交新的恋人",
    "Forbid breaking up with lovers": "禁止与恋人分手",
    "Forbid taking new submissives (by offering them an ownership trial)":
        "禁止接收新的顺从者(通过为他们提供所有权试用期)",
    "Forbid disowning submissives": "禁止放弃顺从者",
    "Allow specific sounds only (such as an animal sound)": "只允许特定的声音(如动物声音)",
    "Garble whispers while gagged (same as normal messages)": "在塞口球时混肴悄悄话(与普通消息相同)",
    "Block OOC chat while gagged (no more misuse of OOC for normal chatting while gagged)":
        "在被堵嘴时阻止OOC聊天(防止在被堵嘴时滥用OOC进行正常聊天)",
    "Block OOC chat (blocks use of OOC in messages)": "阻止OOC聊天(阻止在消息中使用OOC)",
    "Doll talk (allows only short sentences with simple words)": "娃娃聊天(只允许简单词汇的短句)",
    "Forbid saying certain words in chat (based on a configurable blacklist)":
        "禁止在聊天中说某些词(基于可配置的黑名单)",
    "Forbid saying certain words in emotes (based on a configurable blacklist)":
        "禁止在表情中说某些词(基于可配置的黑名单)",
    "Forbid talking openly (in a chat room)": "禁止在聊天室里公开谈话",
    "Limit talking openly (only allow a set number of chat messages per minute)":
        "限制公开聊天(每分钟只允许设定数量的聊天消息)",
    "Forbid using emotes (in a chat room)": "禁止在聊天室使用表情",
    "Limit using emotes (only allow a set number of emotes per minute)": "限制使用表情(每分钟只允许设定数量的表情)",
    "Restrict sending whispers (except to defined roles)": "限制发送私语(除了指定的角色)",
    "Restrict receiving whispers (except from defined roles)": "限制接收私语(除了指定的角色)",
    "Restrict sending beep messages (except to selected members)": "限制发送蜂鸣消息(仅限于选定的成员)",
    "Restrict receiving beeps (and beep messages, except from selected members)":
        "限制接收蜂鸣声(和蜂鸣消息,除非来自选定的成员)",
    "Order to greet club (when entering it through the login portal)": "命令打招呼俱乐部(通过登录门户进入时)",
    "Forbid the antigarble option (BCX's .antigarble command)": "禁止防乱码选项(BCX的 .antigarble 命令)",
    "Force to retype (if sending a message in chat is rejected by BCX due to a rule violation)":
        "强制重新输入(如果违反规则而BCX将拒绝在聊天中发送消息)",
    "Order to greet room (with a settable sentence when entering it newly)":
        "命令向房间打招呼(新进入房间时用设置的句子打招呼)",
    "Greet new guests (when they join the current room)": "欢迎新客人(当他们加入当前房间时)",
    "Establish mandatory words (of which at least one needs to always be included when speaking)":
        "建立强制词汇(说话时必须包含至少一个)",
    "Establish mandatory words in emotes (of which at least one needs to always be included)":
        "在表情中建立强制词汇(发送表情时必须包含至少一个)",
    "Partial hearing (of muffled speech - random & word list based)": "部分听力(受到沉闷言语的影响 - 基于随机和词汇表)",
    "Track rule effect time (counts the time this rule's trigger conditions were fulfilled)":
        "追踪规则生效时间(计算此规则的触发条件得到满足的时间)",
    "Log money changes (spending and/or getting money)": "记录金钱变动(支出和/或获得金钱)",
    "Edit rules permissions": "编辑规则权限",
    "Leave permission mode": "离开权限模式",
    "Change global curses config": "更改全局诅咒配置",
    "Add new curse": "添加新诅咒",
    "Lift all curses": "解除所有诅咒",
    "Place new curses on body, items or clothes": "在身体、物品或衣物上施加新的诅咒",
    "Remove all curses on body, items or clothes": "移除身体、物品或衣物上的所有诅咒",
    "Existing curses set to global curses config are also changed": "全局诅咒配置中已存在的诅咒也会被更改",
    "Activate only global config curses": "仅激活全局配置的诅咒",
    "Switch all added curses to inactive": "将所有已添加诅咒切换为非活动状态",
    "Switch all added curses to active": "将所有已添加诅咒切换为活动状态",
    "Deactivate only global config curses": "仅停用全局配置的诅咒",
    "Curse occupied": "诅咒已占用",
    "Curse all": "全部诅咒",
    "Lower Leg": "小腿",
    "Upper Leg": "大腿",
    "Nipple Piercing": "乳头穿孔",
    "Collar Addon": "颈圈添加物",
    "Collar Restraint": "颈圈约束",
    "Mouth (1)": "嘴巴 (1)",
    "Mouth (2)": "嘴巴 (2)",
    "Mouth (3)": "嘴巴 (3)",
    "Hood": "头套",
    "Devices": "设备",
    "General Addon": "通用附属物",
    "Feet": "脚",
    "Ears Accessory": "耳朵饰品",
    "Page 1 / 2": "第 1 页 / 2",
    "Page 2 / 2": "第 2 页 / 2",
    "Nothing": "无",
    "Curse all occupied slots at once": "一次性诅咒所有已占用的插槽",
    "Curse all slots at once": "一次性诅咒所有插槽",
    "Edit curse slot permissions": "编辑诅咒插槽权限",
    "Character Height": "角色身高",
    "Mouth Style": "嘴巴样式",
    "Pussy Style": "阴部样式",
    "Toggle alphabetical sorting": "切换字母排序",
    "Toggle availability-based sorting": "切换基于可用性的排序",
    "You don't have permission to use this rule": "您没有使用此规则的权限",
    "Show remaining time (Remaining time of keyhold, asylum stay, or GGTS training)":
        "显示剩余时间 (持钥匙时间、收容所逗留时间或 GGTS 训练)",
    "Edit commands permissions": "编辑命令权限",
    "Add": "添加",
    "Authority - Permissions": "权限 - 权限",
    "Behaviour Log - Configuration": "行为日志 - 配置",
    "Curses - Limits": "诅咒 - 限制",
    "Rules - Limits": "规则 - 限制",
    "Commands - Limits": "指令 - 限制",
    "Export": "导出",
    "Import": "导入",
    "Export current config": "导出当前配置",
    "Try to import a previously exported config": "尝试导入先前导出的配置",
    "Enable timer": "启用定时器",
    "Always in effect": "始终生效",
    "in": "在",
    "public": "公共",
    "-1d": "-1天",
    "-1h": "-1小时",
    "-5m": "-5分钟",
    "+5m": "+5分钟",
    "+1h": "+1小时",
    "+1d": "+1天",
    "Removes rule instead of only deactivating it": "删除规则而不仅仅是停用它",
    "Overwrites current trigger conditions": "覆盖当前触发条件",
    "All selected below": "下面全部选中",
    "not in": "不在",
    "private": "私有",
    "[unknown],": "[未知],",
    "Mistress ↑": "女主人 ↑",
    "Whitelist ↑": "白名单 ↑",
    "Friend ↑": "朋友 ↑",
    "Public ↑": "公共 ↑",
    "Owner ↑": "所有者 ↑",
    "Lover ↑": "恋人 ↑",
    "Go back without saving": "返回而不保存",
    "Save all changes and go back": "保存所有更改并返回",
    "Many": "许多",
    "Default": "默认",
    "Exclude body parts": "排除身体部位",
    "Include items/restraints": "包括物品/限制",
    "Copied to clipboard!": "已复制到剪贴板!",
    "Background 1 / 5": "背景 1 / 5",
    "Clothes": "衣服",
    "Select individually": "单独选择",
    "Cosplay items": "角色扮演道具",
    "Restraints/items": "限制/物品",
    "Collar": "项圈",
    "Piercings": "穿孔",
    "Locks": "锁",
    "Background 2 / 5": "背景 2 / 5",
    "Background 3 / 5": "背景 3 / 5",
    "Background 4 / 5": "背景 4 / 5",
    "Background 5 / 5": "背景 5 / 5",
    "Color help": "颜色帮助",
    "<<< Back": "<<< 返回",
    "[EMPTY]": "[空]",
    "Global configuration is not possible on others": "无法在其他角色上进行全局配置",
    "Please select the new lowest role that should still have this permission.":
        "请选择新的最低角色权限等级以保持此权限.",
    "All roles to the left of the selected one will also automatically get access.":
        "所选角色左侧的所有角色也将自动获得访问权限.",
    "WARNING: If you confirm, all permitted roles can remove your access to this and all other permissions!":
        "警告: 如果您确认,所有被允许的角色都可以撤销您对此和所有其他权限的访问权限!",
    '- Authority: Changing minimum access to permission "Allow granting Mistress status" -':
        '- 权限: 更改对 "允许授予女主身份" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow granting Owner status" -':
        '- 权限: 更改对 "允许授予所有者身份" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow granting self access" -':
        '- 权限: 更改对 "允许授予自己访问权限" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow lowest access modification" -':
        '- 权限: 更改对 "允许最低访问级别修改" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow revoking Mistress status" -':
        '- 权限: 更改对 "允许撤销女主身份" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow revoking Owner status" -':
        '- 权限: 更改对 "允许撤销所有者身份" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow viewing list of owners/mistresses" -':
        '- 权限: 更改对 "允许查看所有者/女主列表" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow deleting log entries" -':
        '- 权限: 更改对 "允许删除日志条目" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow to attach notes to the body" -':
        '- 权限: 更改对 "允许在身体上添加注释" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow to configure what is logged" -':
        '- 权限: 更改对 "允许配置记录的内容" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow to praise or scold" -':
        '- 权限: 更改对 "允许表扬或责备" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow to see normal log entries" -':
        '- 权限: 更改对 "允许查看普通日志条目" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow to see protected log entries" -':
        '- 权限: 更改对 "允许查看受保护的日志条目" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow changing colors of cursed objects" -':
        '- 权限: 更改对 "允许更改被诅咒物品的颜色" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow to view who added the curse originally" -':
        '- 权限: 更改对 "允许查看最初添加诅咒的人" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allows handling curses on limited object slots" -':
        '- 权限: 更改对 "允许在限制的对象槽上处理诅咒" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allows handling curses on non-limited object slots" -':
        '- 权限: 更改对 "允许在非限制的对象槽上处理诅咒" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allows to limit/block individual curse object slots" -':
        '- 权限: 更改对 "允许限制/阻止个别诅咒对象槽" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow to view who added the rule originally" -':
        '- 权限: 更改对 "允许查看最初添加规则的人" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allows controlling limited rules" -':
        '- 权限: 更改对 "允许控制限制规则" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allows controlling non-limited rules" -':
        '- 权限: 更改对 "允许控制非限制规则" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allows editing the global rules configuration" -':
        '- 权限: 更改对 "允许编辑全局规则配置" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allows to limit/block specific rules" -':
        '- 权限: 更改对 "允许限制/阻止特定规则" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allows controlling non-limited commands" -':
        '- 权限: 更改对 "允许控制非限制命令" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allows to limit/block specific commands" -':
        '- 权限: 更改对 "允许限制/阻止特定命令" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow changing relationship config for herself" -':
        '- 权限: 更改对 "允许为自己更改关系配置" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow changing relationship config for others" -':
        '- 权限: 更改对 "允许为其他人更改关系配置" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow viewing others in relationship list" -':
        '- 权限: 更改对 "允许查看其他人的关系列表" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow exporting BCX module configurations" -':
        '- 权限: 更改对 "允许导出BCX模块配置" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow importing items using wardrobe" -':
        '- 权限: 更改对 "允许使用衣柜导入物品" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow using the allowactivities command on this player" -':
        '- 权限: 更改对 "允许在此玩家上使用 allowactivities 命令" 权限的最低访问级别 -',
    "Miscellaneous module configuration is not possible on others": "无法在他人身上进行杂项模块配置",
    "Module is deactivated": "模块已停用",
    "Members numbers allowed to summon:": "允许召唤的成员编号:",
    "The text used for summoning:": "用于召唤的文本:",
    "Time in seconds before enforcing summon:": "强制召唤前的时间(秒):",
    "Minimum role that is allowed to leash:": "允许牵引的最低角色:",
    "Allow safeword use": "允许使用安全词",
    "Hearing whitelist": "听觉白名单",
    "Seeing whitelist": "视觉白名单",
    "Members numbers still heard while hearing impaired:": "听觉受损时仍然可听到的成员编号:",
    "Also understand if those are speech impaired": "是否同时理解言语障碍",
    "New leave time in seconds:": "新的离开时间(秒):",
    "Set this player's nickname:": "设置此玩家的昵称:",
    "Restore the previous nickname at rule end": "在规则结束时恢复先前的昵称",
    "Set the allowed sounds:": "设置允许的声音:",
    "All forbidden words:": "所有禁止的词语:",
    "Amount of minutes, before being considered inactive:": "被视为不活跃之前的分钟数:",
    "Also log getting money": "也记录获取金钱",
    "Still allow unlocking owner locks or items": "仍然允许解锁主人锁或物品",
    "Still allow unlocking lover locks or items": "仍然允许解锁恋人锁或物品",
    "Minimum role able to request counted time:": "能够请求计时的最低角色:",
    "The sentences that will be shown at random:": "将随机显示的句子:",
    "Frequency of a sentence being shown (in minutes):": "句子显示的频率(分钟):",
    "Item permission": "物品权限",
    "Everyone, no exceptions": "所有人,无例外",
    "BCX: Rule changed your 'Item permission' setting": "BCX: 规则更改了您的'物品权限'设置",
    "Everyone, except blacklist": "所有人,除了黑名单",
    "Owner, Lovers, whitelist & Dominants": "主人,恋人,白名单和支配者",
    "Owner, Lovers and whitelist only": "仅主人,恋人和白名单",
    "BCX: Rule changed your 'Locks on you can't be picked' setting": "BCX: 规则更改了您的'不能撬开您身上的锁'设置",
    "Cannot enter single-player rooms when restrained": "被束缚时无法进入单人房间",
    "Hearing impairment:": "听觉受损:",
    "Light": "轻度",
    "Medium": "中度",
    "Heavy": "重度",
    "Eyesight impairment:": "视觉受损:",
    "Player sees the effect also on herself": "玩家也能在自己身上看到效果",
    "Hide names and icons during the effect": "在效果期间隐藏名字和图标",
    "Orgasm attempts will be fixed to:": "尝试高潮将被固定为:",
    "Edge": "边缘",
    "Ruin": "毁灭",
    "Prevent resisting": "防止抵抗",
    "Minimum role that gets admin:": "获得管理员权限的最低角色:",
    "Player loses admin afterwards": "玩家在之后失去管理员权限",
    "Edit this player's profile description:": "编辑此玩家的个人描述:",
    "Members numbers that can always be seen:": "始终可见的成员编号:",
    "Mark poses as being allowed or forbidden:": "将姿势标记为允许或禁止:",
    "Only joining rooms with these names is allowed:": "只允许加入具有这些名称的房间:",
    "Minimum role preventing room leaving:": "阻止离开房间的最低角色:",
    "Favorite: Listed first in overview": "收藏: 在概览中首先列出",
    "Still allow removing low difficulty items": "仍然允许移除低难度物品",
    "Only forbid tying people with higher dominance": "仅禁止对更高支配值的玩家进行绑缚",
    "Minimum role forbidden to blacklist:": "被禁止添加到黑名单的最低角色:",
    "The level of forced garbling": "强制性的语音失真程度",
    "Words that can always be understood:": "始终可以理解的单词:",
    "Some words are randomly understood": "一些单词将随机理解",
    "Can also understand gagged persons": "也能理解被塞口球的玩家",
    "At least one of these words always needs to be used:": "这些单词中至少需要始终使用一个:",
    "Also affect whispered messages": "也影响私语消息",
    "Member numbers still allowed to send beeps:": "仍然允许发送蜂鸣消息的成员编号:",
    "Auto replies blocked sender with this:": "自动回复被屏蔽发件人使用此:",
    "Only in effect when unable to use hands": "仅在无法使用双手时生效",
    "Member numbers that will be greeted:": "将被问候的成员编号:",
    "The sentence that has to be used to greet any joined room:": "必须用于问候任何加入的房间的句子:",
    "Also forbid emote messages before greeting": "还禁止在问候之前发送表情消息",
    "The sentence that will be used to greet new guests:": "将用于问候新客人的句子:",
    "Restrict receiving beeps": "限制接收蜂鸣消息",
    "Order to greet club": "命令问候俱乐部",
    "Forbid the antigarble option": "禁止反语音失真选项",
    "Force to retype": "强制重新输入",
    "Order to greet room": "命令问候房间",
    "Greet new guests": "问候新客人",
    "Page 5 / 5": "第5页 / 5",
    "Restrict entering rooms": "限制进入房间",
    "Prevent leaving the room": "防止离开房间",
    "Forbid freeing self": "禁止解救自己",
    "Forbid tying up others": "禁止绑缚他人",
    "Prevent blacklisting": "防止加入黑名单",
    "Prevent whitelisting": "防止加入白名单",
    "Forbid the antiblind command": "禁止使用反盲指令",
    "Force garbled speech": "强制语音失真",
    "Partial hearing": "部分听觉",
    "Establish mandatory words in emotes": "在表情中设定强制的单词",
    "Establish mandatory words": "设定强制的单词",
    "Enforce faltering speech": "强制支支吾吾的说话",
    "Page 4 / 5": "第4页 / 5",
    "Control ability to orgasm": "控制高潮的能力",
    "Secret orgasm progress": "秘密高潮进度",
    "Room admin transfer": "房间管理员转让",
    "Limit bound admin power": "限制被束缚的管理员权限",
    "Control profile online description": "控制个人资料在线描述",
    "Always carry a suitcase": "始终携带手提箱",
    "Hide online friends if blind": "如果失明则隐藏在线好友",
    "Forbid wardrobe use on self": "禁止使用衣柜",
    "Page 3 / 5": "第3页 / 5",
    "Log money changes": "记录货币变动",
    "Forbid using keys on self": "禁止自己使用钥匙",
    "Track rule effect time": "追踪规则生效时间",
    "Listen to my voice": "倾听我的声音",
    "Force 'Item permission'": "强制'物品权限'",
    "Force 'Locks on you can't be picked'": "强制'无法打开自己身上的锁'",
    "Force 'Cannot enter single-player rooms when restrained'": "强制'被束缚时无法进入单人房间'",
    "Forbid using locks on self": "禁止对自己使用锁",
    "Sensory deprivation: Sound": "感觉剥夺: 听觉",
    "Sensory deprivation: Sight": "感觉剥夺: 视觉",
    "Garble whispers while gagged": "戴口球时扭曲私语",
    "Page 2 / 5": "第2页 / 5",
    "Forbid changing difficulty": "禁止更改难度",
    "Prevent usage of all activities": "阻止使用所有交互活动",
    "Forbid mainhall maid services": "禁止主厅女仆服务",
    "Forbid the action command": "禁止使用动作命令",
    "Usage blocked by BCX": "被BCX禁止使用",
    "Filter items": "过滤物品",
    "Select what shall be hidden:": "选择要隐藏的内容:",
    "Icons": "图标",
    "Also hide emoticons during the effect": "在生效期间也隐藏表情符号",
    "Icons/Bar": "图标/条",
    "Icons/Bar/Names": "图标/条/名称",
    "Minimum role that is allowed:": "允许的最低角色:",
    "Sexual activities - Activation": "性活动 - 激活",
    "Allow with a hybrid meter": "允许使用混合仪表",
    "Meter visibility": "仪表可见性",
    "Show arousal to everyone": "向所有人显示高潮条",
    "Show if they have access": "如果他们有权限则显示",
    "BCX: Rule changed your 'Arousal meter' setting": "BCX: 规则更改了你的'高潮条'设置",
    "Allow with a locked meter": "允许使用锁定的仪表",
    "Disable sexual activities": "禁用性活动",
    "Allow without a meter": "允许没有仪表",
    "Allow with a manual meter": "允许使用手动仪表",
    "Show to yourself only": "仅自己可见",
    "Block advanced vibrator modes": "阻止高级震动器模式",
    "Speech stuttering": "语言结巴",
    "Aroused & vibrated": "激动和振动",
    "Never stutter": "永不结巴",
    "When you're aroused": "当你兴奋时",
    "When you're vibrated": "当你被振动时",
    "Show AFK bubble": "显示离开状态气泡",
    "BCX: Rule changed your 'Show AFK bubble' setting": "BCX: 规则更改了你的'显示离开状态气泡'设置",
    "Allow others to alter your whole appearance": "允许他人更改你的整体外观",
    "Prevent others from changing cosplay items": "阻止他人更改角色扮演物品",
    "Sensory deprivation setting": "感官剥夺设置",
    "Disable examining when blind": "失明时禁用检查",
    "Hide others' messages": "隐藏他人的消息",
    "Hide names": "隐藏名称",
    "BCX: Rule changed your 'Sensory deprivation setting' setting": "BCX: 规则更改了你的'感官剥夺设置'设置",
    "Total": "总计",
    "Hide non-adjacent players while partially blind": "部分失明时隐藏非相邻玩家",
    "Garble chatroom names and descriptions while blind": "失明时混淆聊天室名称和描述",
    "Keep all restraints when relogging": "重新登录时保留所有约束",
    "Players can drag you to rooms when leashed": "当被牵引时其他玩家可以拖动你到其他房间",
    "Return to chatrooms on relog": "重新登录时返回聊天室",
    "Auto-remake rooms": "自动重新创建房间",
    "BCX: Rule changed your 'Return to chatrooms on relog' setting": "BCX: 规则更改了你的'重新登录时返回聊天室'设置",
    "Events while plugged or vibed": "插入或振动时的事件",
    "Allow item tint effects": "允许物品色调效果",
    "BCX: Rule changed your 'Allow item blur effects' setting": "BCX: 规则更改了你的'允许物品模糊效果'设置",
    "Flip room vertically when upside-down": "倒置时垂直翻转房间",
    "BCX: Rule changed your 'Flip room vertically when upside-down' setting":
        "BCX: 规则更改了你的'倒置时垂直翻转房间'设置",
    "Prevent random NPC events": "防止随机NPC事件",
    "Max. character length of any word:": "任何单词的最大字符长度:",
    "Max. number of words per message:": "每条消息的最大单词数:",
    "Maximum allowed number of chat messages per minute (> 0):": "每分钟允许的最大聊天消息数 (> 0):",
    "Maximum allowed number of emotes per minute (> 0):": "每分钟允许的最大表情数 (> 0):",
    "Minimum role whispering is still allowed to:": "仍允许接收悄悄话的最低角色:",
    "Minimum role still allowed to send whisper:": "仍允许发送耳语的最低角色:",
    "Member numbers still allowed to be beeped:": "仍允许蜂鸣消息的玩家编号:",
    "Forbid saying certain words in emotes": "禁止在表情中说某些词",
    "Forbid talking openly": "禁止公开讲话",
    "Limit talking openly": "限制公开讲话",
    "Forbid using emotes": "禁止使用表情",
    "Limit using emotes": "限制使用表情",
    "Restrict sending whispers": "限制发送耳语",
    "Restrict receiving whispers": "限制接收耳语",
    "Restrict sending beep messages": "限制发送蜂鸣消息",
    "Page 8 / 8": "第8页 / 8",
    "Force 'Keep all restraints when relogging'": "强制'重新登录时保留所有约束'",
    "Force 'Players can drag you to rooms when leashed'": "强制'被牵引时其他玩家可以拖动你到其他房间'",
    "Force 'Return to chatrooms on relog'": "强制'重新登录时返回聊天室'",
    "Force 'Events while plugged or vibed'": "强制'插塞或震动时的事件'",
    "Force 'Allow item tint effects'": "强制'允许物品染色效果'",
    "Force 'Allow item blur effects'": "强制'允许物品模糊效果'",
    "Force 'Flip room vertically when upside-down'": "强制'上下颠倒时垂直翻转房间'",
    "Force 'Prevent random NPC events'": "强制'阻止随机NPC事件'",
    "Forbid taking new submissives": "禁止接收新的顺从者",
    "Block OOC chat while gagged": "堵住口球时禁止OOC聊天",
    "Doll talk": "娃娃聊天",
    "Page 7 / 8": "第7页 / 8",
    "Prevent using items of others": "阻止使用他人的物品",
    "Prevent changing own emoticon": "阻止更改自己的表情符号",
    "Force-hide UI elements": "强制隐藏UI元素",
    "Forbid using remotes on self": "禁止对自己使用遥控器",
    "Forbid picking locks on self": "禁止撬自己身上锁",
    "Prevent using BCX permissions": "阻止使用 BCX 权限",
    "Force 'Allow safeword use'": "强制 '允许使用安全词'",
    "Forbid club owner changes": "禁止更改俱乐部主人",
    "Allow specific sounds only": "仅允许特定声音",
    "Block OOC chat": "屏蔽 OOC 聊天",
    "Forbid saying certain words in chat": "禁止在聊天中说特定的词语",
    "Track BCX activation": "追踪 BCX 激活",
    "Allow changing the whole appearance": "允许更改整体外观",
    "Force 'Arousal meter'": "强制'高潮条'",
    "Force 'Block advanced vibrator modes'": "强制'阻止高级震动器模式'",
    "Force 'Arousal speech stuttering'": "强制'Arousal言语结巴'",
    "Force 'Show AFK bubble'": "强制'显示AFK气泡'",
    "Force 'Allow others to alter your whole appearance'": "强制'允许他人更改你的整体外观'",
    "Force 'Prevent others from changing cosplay items'": "强制'阻止他人更改角色扮演物品'",
    "Force 'Sensory deprivation setting'": "强制'感官剥夺设置'",
    "Force 'Hide non-adjacent players while partially blind'": "强制'在部分失明时隐藏非相邻玩家'",
    "Force 'Garble chatroom names and descriptions while blind'": "强制'在失明时混淆聊天室名称和描述'",
    "Page 6 / 8": "第6页 / 共8页",
    "Forbid looking at room admin UI": "禁止查看房间管理UI",
    "Forbid using GGTS": "禁止使用GGTS",
    "Prevent working as a club slave": "阻止作为俱乐部奴隶工作",
    "Page 5 / 8": "第5页 / 共8页",
    "Page 4 / 8": "第4页 / 共8页",
    "Page 3 / 8": "第3页 / 共8页",
    "Page 2 / 8": "第2页 / 共8页",
    "BCX: You are not allowed to talk openly in chatrooms!": "BCX: 你不能在聊天室中公开说话!",
    "BCX: A BCX rule prevents you from using this while unable to see!":
        "BCX: 一个BCX规则阻止你在无法看到的情况下使用这个!",
    "EBCH: Turn on Ungarble (Hearing Whitelist)": "EBCH: 打开去噪(听觉白名单)",
    "EBCH: Turn off custom notifications": "EBCH: 关闭自定义通知",
    "EBCH: Turn on chatlogging": "EBCH: 打开聊天记录",
    "Instant Messenger (Disabled by BCX)": "即时通讯(被BCX禁用)",
    "EBCH: Turn on Ungarble (all)": "EBCH: 打开去噪(全部)",
    "EBCH: Turn on custom notifications": "EBCH: 打开自定义通知",
    "EBCH: Turn off ungarble": "EBCH: 关闭去噪",
    "EBCH: Preparing DB.": "EBCH: 准备数据库.",
    "EBCH: DB Ready.": "EBCH: 数据库准备就绪.",
    "EBCH: Turn off chatlogging": "EBCH: 关闭聊天记录",
    "EBCH: Pose UI on": "EBCH: 打开POSE UI",
    "BaseHand": "基础手势",
    "HandsUp": "举手",
    "HandsHigh": "高举双手",
    "BackLoose": "轻松背手",
    "BackTight": "紧绷背手",
    "Standing": "站立",
    "Kneeling": "跪姿",
    "KneelSpr": "跪地张腿",
    "StandCl": "站立闭合",
    "StandSpr": "站立张退",
    "BellyLie": "仰卧",
    "AllFours": "四脚着地",
    "EBCH: Pose UI off": "EBCH: 关闭POSE UI",
    "Base Hands": "基础手势",
    "Hands Up": "举手",
    "Hands Up High": "高举双手",
    "Back Loose": "轻松背手",
    "Back Tight": "紧绷背手",
    "Stand": "站立",
    "Kneel": "跪姿",
    "Kneel Spread": "跪地张腿",
    "Standing Closed Legs": "站立闭合腿",
    "Standing Spread": "站立张腿",
    "Belly Lie": "仰卧",
    "All Fours": "四脚着地",
    "BCX: You are not allowed to use emotes in chatrooms!": "BCX: 不允许在聊天室使用表情!",
    "BCX: You are not allowed to change the emoticon!": "BCX: 不允许更改表情!",
    "Toggle Shared Crafts": "切换共享工艺",
    "Modify layering priority": "修改图层优先级",
    "Adjust individual layers": "调整单独图层",
    "Set item priority": "设置物品优先级",
    "Choose clothing": "选择服装",
    "Choose body parts": "选择身体部位",
    "Choose cosplay items": "选择角色道具",
    "How does it work?": "它是如何操作的?",
    "Control nickname": "控制昵称",
    "Ready to be summoned": "准备好被召唤",
    "If you are permitted, this screen enables you to view, add, or remove the BCX-only roles 'Owner' and 'Mistress', which expand the classic roles of BC such as Bondage Club's Owner and the Lovers. The hierarchy of all roles that can be used to set various things in BCX can be seen on the right. The higher up a role is, the more authority it has. For instance, if something applies or is permitted for a Mistress, it also always is for an Owner. Any number of Owners and Mistresses can be set. Check their current power over BCX with the button on the right.":
        "如果您被允许, 此界面使您能够查看、添加或删除仅限BCX的角色'主人'和'女主人', 这扩展了BC的经典角色, 如 Bondage Club 的主人和恋人. 可用于在BCX中设置各种内容的所有角色的层次结构显示在右侧. 角色越靠近顶端, 其权限越大. 例如, 如果某事适用于女主人或为其允许,那么主人也始终如此. 可以设置任意数量的主人和女主人. 使用右侧的按钮检查它们对 BCX 的当前权限.",
    "we are happy you are interested in our extension for the Bondage Club (BC) in which we invest a lot of our free time and love. If you have any questions, suggestions, or encounter any bugs, please feel free to get in touch with us on Discord. A button linking to it is in the main menu.":
        "我们很高兴您对我们在其中投入了很多空闲时间和热情对 Bondage Club (BC) 扩展感兴趣. 如果您有任何问题、建议或遇到任何错误,请随时通过 Discord 与我们联系. 主菜单中有一个链接到Discord的按钮.",
    "The heart of BCX: Allows to configure the permissions to set up and use most of BCX. Default settings depend on the initial BCX setup preset selected. Self access is the checkbox next to every permission and the lowest access role is to its right. Example: If 'allow forbidding self access', 'allow granting self access', 'allow lowest access modification' have the checkbox removed and lowest role is 'Owner', then current and newly added BCX owners and the BC owner can get full control over any permissions they have access to. So careful with those three permissions!":
        "BCX的核心: 允许配置设置和使用 BCX 的大多数权限. 默认设置取决于所选的初始 BCX设置预设. 自访问是每个权限旁边的复选框, 最低访问角色在其右侧. 例如: 如果'允许禁止自访问', '允许授予自访问', '允许最低访问修改' 的复选框已移除, 且最低角色为'主人', 那么当前和新添加的 BCX所有者 以及 BC所有者 可以完全控制其访问权限的任何权限. 因此请小心处理这三个权限!",
    "This screen shows logs of important events. What is logged depends on the logging configuration, which can be viewed/edited via the button to the right. Log entries can have normal or protected visibility. Access to those as well as removing entries or the configuration is determined by the according authority module permission settings. The log can document the BCX's user's conduct, any rule violations, important changes made to BCX settings, curses or rules, and notes from other people.":
        "此界面显示重要事件的日志. 记录的内容取决于日志配置, 可以通过右侧的按钮查看/编辑. 日志条目可以具有普通或受保护的可见性. 访问这些条目以及删除条目或配置是由相应的权限模块权限设置确定的. 日志可以记录BCX用户的行为, 任何违规行为, 对BCX设置的重要更改, 诅咒或规则, 以及其他人的注释.",
    "This screen determines what is logged in the behaviour log and what the visibility of each type of log messages is. 'Yes' means this log type has normal visibility, while 'protected' means only roles who have permission to view protected entries can view them. 'No' means that this log type is not logged at all. In the permission settings view of the authority module, the permissions of this log module can be configured.":
        "此界面确定在行为日志中记录了什么以及每种类型的日志消息的可见性. '是'表示此日志类型具有普通可见性, 而 '受保护' 表示只有具有查看受保护条目权限的角色才能查看它们. '否' 表示根本不记录此日志类型. 在权限模块的权限设置视图中, 可以配置此日志模块的权限.",
    "This screen shows all active curses on the player, including many information, such as duration, if it is a cursed item/clothing/body slot or a blocked item or clothing slot that forces to stay unrestrained or naked there. Clicking on the button with the cog icon in the middle of each row moves you to a new screen that allows to configure the curse (if you have permission). When the cog icon has a blue aura, that means that the curse's conditions are the same as the global config. If permitted, you can remove single curses with the 'X' button.":
        "此界面显示玩家身上的所有活动诅咒, 包括许多信息, 例如持续时间、是否为 被诅咒的物品/服装/身体槽 或 强制保持未受限制 或 赤裸的封锁物品 或 服装槽. 单击每行中间带有齿轮图标的按钮会将您移动到一个新界面, 允许配置诅咒(如果您有权限). 当齿轮图标带有蓝色光环时, 这意味着诅咒的条件与全局配置相同. 如果允许, 您可以使用 'X'按钮删除单个诅咒.",
    "The settings on this page are the global/default settings for all newly added curses. Changes to the trigger conditions are also applied to existing curses that are (still) set to global curses configuration, though. Exception is if a timer is set here. Such a timer only applies to newly created curses.":
        "此页面的设置是所有新添加的诅咒的 全局/默认设置. 对触发条件的更改也适用于仍设置为 全局诅咒配置的现有诅咒, 但例外情况是如果此处设置了 计时器. 这样的计时器仅适用于新创建的诅咒.",
    "Here, you can add a curse to any empty slot (white) which will keep it empty or on any worn item (gold) which will prevent removal. You add the curse by simply clicking the slot which then becomes purple to indicate that it is now cursed. Grey slots indicate that you have no access to them, due to them being blocked or due to your permission settings. Slots can be limited/blocked via the settings button on the very right. The screen has a second page for the character's body slots.":
        "在这里, 您可以将诅咒添加到任何空槽(白色), 使其保持空白, 或添加到任何佩戴的物品(金色), 使其无法移除. 您只需点击槽即可添加诅咒, 然后该槽变为紫色, 表示现在已受到诅咒. 灰色槽表示您无权访问它们, 这是由于它们被封锁或由于您的权限设置. 可以通过最右侧的设置按钮限制/封锁槽. 界面的第二页用于角色的身体槽.",
    "This screen shows all active rules for the player, including many information, such as duration, the rule type and little status icons that show if the rule is enforced and/or transgressions are logged. Clicking on the button with the cog icon in the middle of each row moves you to a new screen that allows to configure the rule (if you have permission). When the cog icon has a blue aura, then that means that the rule's conditions are the same as the global config. If permitted, you can remove single rules with the 'X' button.":
        "此界面显示玩家的所有活动规则, 包括许多信息, 例如持续时间、规则类型和小的状态图标, 显示规则 是否正在执行 和/或 是否记录了违规行为. 单击每行中间带有齿轮图标的按钮会将您移动到一个新界面, 允许配置规则(如果您有权限). 当齿轮图标带有蓝色光环时, 这意味着规则的条件与全局配置相同. 如果允许, 您可以使用'X'按钮删除单个规则.",
    "On this screen you can see the available commands for the player. Clicking on one shows a more detailed description of it. Greyed out commands indicate that you have no access to them due to being blocked or due to your permission settings. Commands can be limited/blocked via the settings button on the very right. Commands will be used in the chat room's chat by whispering them with a '!' before the command to another player. Note: SOME of the commands can also be used on yourself with a leading '.' instead of '!' (e.g. '.eyes close')":
        "在此界面上, 您可以查看玩家的可用命令. 单击其中一个会显示更详细的描述. 灰色的命令表示由于受阻或由于权限设置而无法访问它们. 可以通过最右侧的设置按钮 限制/封锁 命令. 命令将在聊天室的聊天中使用, 通过向其他玩家用 '!' 在命令之前轻声呢喃给出. 注意: 其中一些命令也可以在自己身上使用, 以 '.' 而不是 '!' 为前缀(例如'.eyes close')",
    "Here you can cycle commands between being not limited, limited and blocked. Blocked means no one can use this command, while limited means only roles that have the permission to use limited commands can trigger them in that chat. There is no need to save changes as they are instantly in effect.":
        "在这里, 您可以在 不受限制、受限制 和 受阻 之间循环命令. 阻塞意味着没有人可以使用此命令, 而有限意味着只有具有使用有限命令权限的角色才能在该聊天中触发它们. 无需保存更改, 它们会立即生效.",
    "This screen lets you add custom nicknames for other club members. The set custom name replaces the added character's real name / BC-nickname in this player's chat, except within chat commands, which are considered OOC. You can also enforce the custom name so that the player is blocked from sending a chat message / whisper that use the character's name / BC-nickname while with her. The player cannot have multiple custom names set for a single character. A character who has a custom name set on this screen can always see their own set custom name in this list.":
        "此界面允许您为其他俱乐部成员添加自定义昵称. 设置的自定义名称将替换此玩家聊天中添加的角色姓名/BC昵称, 但在被视为OOC的聊天命令中除外. 您还可以强制执行自定义名称, 以阻止玩家在与其一起使用角色的名称/BC昵称的聊天消息/耳语. 对于单个角色, 玩家不能设置多个自定义名称. 在此界面上设置了自定义名称的角色始终可以在此列表中看到其自己设置的自定义名称.",
    "Please select the module feature you want to backup or import from a previous export. After storing the exported texts, you can later on use them again, e.g. for switching between cursed outfits or different rule sets. These exports are compatible between different BCX users and can be used by everyone with BCX who is permitted to make changes to the according module. For instance, if an owner has the permission to control limited AND non-limited rules on the sub, she is with that also allowed to import previously exported rules that are not blocked.":
        "请选择您要备份或从以前的导出中导入的模块功能. 在存储了导出的文本之后, 您以后可以再次使用它们, 例如在诅咒的服装之间切换或不同的规则集之间切换. 这些导出在不同的BCX用户之间是兼容的, 并且可以由具有更改相应模块的权限的BCX的每个人使用. 例如, 如果所有者有权限控制子女的有限和非有限规则, 那么她也被允许导入先前未被阻止的导出规则.",
    "This screen offers various settings to configure your Bondage Club experience in general, such as enabling/disabling the typing indicator that shows other BCX users an icon when you are currently typing something to public chat or whispering something to only them. The cheats are only temporarily active as long as they are set; items that were only given via a cheat are then also gone again.":
        "此界面提供各种设置, 以一般配置您在Bondage Club中的体验, 例如启用/禁用打字指示器, 当您当前在公共聊天中输入或向他们私下耳语时, 它会向其他BCX用户显示一个图标. 作弊只在设置时是临时的；仅通过作弊获得的物品也将消失.",
    "On this screen you can establish new rules for the player by simply clicking any rule template. After clicking on it, you can edit the rule's configuration. Purple rule templates indicate, that they are already in use; greyed out ones, that you have no access to them due to being blocked or due to your permission settings. Rule templates can be limited/blocked via the settings button on the very right. Note: If you want to be able to log rule violations, this type of log entry may need to be allowed in the configuration page of the behavior log module.":
        "在此界面上, 您可以通过简单地单击任何规则模板来为玩家建立新规则. 单击后, 您可以编辑规则的配置. 紫色的规则模板表示它们已在使用中；灰色的模板表示由于被阻止或由于权限设置而无法访问它们. 规则模板可以通过最右侧的设置按钮限制/封锁. 注意: 如果要能够记录违规行为, 可能需要在行为日志模块的配置页面中允许此类型的日志条目.",

    "More": "更多",
    "More options [BCX]": "更多选项 [BCX]",
    "Standardize your room description so the room's purpose is clear and it can easily be filtered:":
        "标准化您的房间描述, 以便清晰显示房间的用途, 并且可以轻松进行过滤: ",
    "Create a theme room": "创建一个主题房间",
    "Templates for storing / overwriting current room information & settings (press a name to toggle auto-apply)":
        "用于存储/覆盖当前房间信息和设置的模板(按名称切换自动应用)",
    "- empty template slot -": "- 空模板槽 -",
    "Load": "加载",
    "    Save": "    保存",
    "1. Select the room type:": "1. 选择房间类型: ",
    "2. Optionally, select one room setting:": "2. 可选地, 选择一个房间设置: ",
    "3. Optionally, select limits for the room:": "3. 可选地, 选择房间的限制: ",
    "4. Optionally, write a room introduction message/greeting that everyone joining will see as emote:":
        "4. 可选地, 编写一个房间介绍消息/欢迎词, 所有加入的人都会看到其作为表情. ",
    "AFK/Storage": "AFK/存储",
    "Chill/Chat": "休闲/聊天",
    "Tying all up": "全部捆绑",
    "Game": "游戏",
    "Roleplaying": "角色扮演",
    "Kidnap/Danger": "绑架/危险",
    "Market/Auction": "市场/拍卖",
    "Undefined": "未定义",
    "Adventure": "冒险",
    "Historic": "历史",
    "Romantic": "浪漫",
    "SciFi": "科幻",
    "Fantasy": "奇幻",
    "Modern": "现代",
    "School": "学校",
    "no-anal": "无屁眼交易",
    "no-animals": "无动物",
    "no-fantasy": "无幻想",
    "no-limits": "无限制",
    "no-males": "无男性",
    "no-sexual": "无性行为",
    "no-tentacles": "无触手",
    "Blocked items:": "已屏蔽的物品:",
    "OK": "确定",
    "Import everything onscreen": "导入界面上的所有内容",
    "Export everything onscreen": "导出界面上的所有内容",
    "Hierachy of roles": "角色层次结构",
};

export { translation };
