const translation = {
    // BCX
    "You can find BCX here ►": "在此处可找到 BCX ►",
    "- Bondage Club Extended -": "- Bondage Club 扩展 -",
    "BCX TUTORIAL: Welcome": "BCX教程: 欢迎",
    "Loading...": "加载中...",
    "BCX TUTORIAL: Adding curses": "BCX教程: 添加诅咒",
    "BCX TUTORIAL: Quick overview": "BCX教程: 快速概述",
    "BCX TUTORIAL: End of introduction": "BCX教程: 介绍结束",
    "BCX TUTORIAL: Curses module overview": "BCX教程: 诅咒模块概述",
    "BCX TUTORIAL: New chat room icons": "BCX教程: 新的聊天室图标",
    "BCX TUTORIAL: Logging module screen": "BCX教程: 日志模块界面",
    "BCX TUTORIAL: Rules module overview": "BCX教程: 规则模块概述",
    "BCX TUTORIAL: Logging configuration screen": "BCX教程: 日志配置界面",
    "BCX TUTORIAL: Introduction to roles and permissions": "BCX教程: 角色和权限介绍",
    "BCX TUTORIAL: Permission system base principles": "BCX教程: 权限系统的基本原理",
    "BCX TUTORIAL: Limiting curse slots / rules": "BCX教程: 限制诅咒 插槽/规则",
    "BCX TUTORIAL: General permission examples": "BCX教程: 一般权限示例",
    "BCX TUTORIAL: Permission setup example 1": "BCX教程: 权限设置示例1",
    "BCX TUTORIAL: Permission setup example 2": "BCX教程: 权限设置示例2",
    "BCX TUTORIAL: Permission system overview": "BCX教程: 权限系统概述",
    "BCX TUTORIAL: Commands module overview": "BCX教程: 指令模块概述",
    "BCX TUTORIAL: Trigger conditions": "BCX教程: 触发条件",
    "BCX TUTORIAL: Adding a rule": "BCX教程: 添加规则",
    "BCX TUTORIAL: Chat commands": "BCX教程: 聊天指令",
    "Please choose a preset, which sets your default experience, permissions and configuration.":
        "请选择一个预设,以设定您的默认体验、权限和配置.",
    "Note: You can change the defaults, but changing to another preset is not possible without resetting BCX fully.":
        "注意: 您可以更改默认值, 但在不完全重置 BCX 的情况下, 无法更改为另一个预设.",
    "Dominant": "支配者",
    "This preset is for dominants who": "此预设适用于",
    "never intend to submit. Therefore,": "从不想屈服的支配者.因此, ",
    "most modules are not loaded at": "大多数模块在启动时.",
    "start. That said, you can still use": "未加载.话虽如此, 您仍然可以使用",
    "the BCX graphical user interface": "BCX 的图形用户界面",
    "on other BCX users to use actions,": "对其他 BCX 用户采取您有权限的操作,",
    "you have permission for, on them,": "对他们, ",
    "same as with all other presets.": "与所有其他预设相同.",
    "Switch/Exploring": "转换/探索",
    "This preset is for switches who": "此预设适用于那些",
    "are sometimes dominant and": "有时处于主导地位且,",
    "sometimes submissive, enabling": "有时处于服从地位, 从而",
    "them to explore BCX slowly, while": "让他们能够慢慢探索 BCX, 同时",
    "having full control over all of its": "完全掌控其所有的",
    "settings and features.": "设置和功能.",
    "Easily try out all features": "轻松试用所有功能",
    "Submissive": "服从者",
    "This preset is for submissives,": "此预设是为服从者准备的,",
    "who want to give some of their": "那些想要交出部分",
    "control to selected dominants and": "控制权给选定的支配者和",
    "lovers, giving only them authority": "爱人, 只赋予他们权限",
    "over some of BCX's settings. You": "对 BCX 的部分设置.您",
    "can irreversably give away more": "可以不可逆转地交出更多",
    "and more control, when you want.": "控制权, 只要您愿意.",
    "Similar to Ace's Cursed Script": "类似于 Ace 的诅咒脚本",
    "Slave": "奴隶",
    "This preset is a much more": "此预设是更为",
    "extreme submissive experience,": "极端的顺从体验, ",
    "not leaving much control over the": "没有留下太多对",
    "settings and permissions to you,": "设置和权限的控制给您, ",
    "thus enabling others to use many": "从而使别人能够使用许多",
    "of BCX's features on you. Owners": "BCX 在您身上的功能.所有者",
    "can even unblock the most extreme": "甚至可以解除最极端的",
    "settings, if they desire so.": "设置, 如果他们希望这样做的话.",
    "BCX: First time init finalized": "BCX: 首次初始化完成",
    "This is the latest version": "这是最新版本",
    "View changelog": "查看更新日志",
    "Enable typing indicator": "启用输入指示器(打字中的气泡)",
    "Show BCX icons above characters in chatroom": "在聊天室中的角色上方显示 BCX 图标",
    "Show your BCX Supporter Heart to all BCX users": "向所有 BCX 用户展示您的 BCX 支持者之心",
    "Cheat: Give yourself the mistress padlock and its key": "作弊：给自己女王锁及其钥匙",
    "Cheat: Give yourself the pandora padlock and its key": "作弊：给自己潘多拉魔盒锁及其钥匙",
    "- Permanent deletion of ALL Bondage Club Extended data -": "- 永久删除所有 Bondage Club 扩展数据 -",
    "Use the following text to auto fill the chat room search field:": "使用以下文本自动填充聊天室搜索字段:",
    "Hide BC's typing & wardrobe icon on users showing BCX one": "在显示 BCX 的用户上隐藏 BC 的打字和衣柜图标",
    "Cheat: 阻止随机 NPC 事件 (kidnappings, ransoms, asylum, club slaves)":
        "作弊：阻止随机 NPC 事件(绑架、赎金、收容所、俱乐部奴隶)",
    "Enable status indicator showing when you are in any player's BCX menu, biography, or wardrobe":
        "当您处于任何玩家的 BCX 菜单、个人简介(bio)或衣柜中时, 启用显示状态的气泡",
    "If you confirm, all BCX data (including settings, curses, logs, ...) will be permanently deleted!":
        "如果您确认, 所有 BCX 数据(包括设置、诅咒、日志……)将被永久删除!",
    "you confirm, all BCX data (including settings, curses, logs, ...) will be permanently deleted!":
        "您确认, 所有 BCX 数据(包括设置、诅咒、日志……)将被永久删除!",
    "As part of the deletion process, the window will reload, logging you out of your account.":
        "作为删除过程的一部分, 窗口将重新加载, 使您退出您的帐户.",
    "You will be able to use BCX again, but none of your current data will be coming back!":
        "您将能够再次使用 BCX, 但您当前的任何数据都不会恢复!",
    "Cheat: Prevent loosing Mistress status when reputation falls below 50 dominance":
        "作弊：当声望低于 50 支配力时防止失去女主人地位",
    "Use the extended wardrobe importer as default": "使用扩展的衣橱导入器作为默认选项",
    "This action cannot be undone!": "此操作不可撤销!",
    "Authority module permissions": "权限模块的权限",
    "Hierarchy of roles:": "角色权限的层级：",
    "Actual character name": "实际角色名称",
    "Lowest permitted role": "最低允许角色",
    "Enforce speaking it?": "强制说出吗?",
    "Export compressed": "导出压缩",
    "Member Number:": "成员编号:",
    "Behaviour Log": "行为日志",
    "Custom name": "自定义名称",
    "- Warning -": "- 警告 -",
    "Deleting...": "删除中…",
    "is permitted": "被允许",
    "New name:": "新名称:",
    "Commands": "指令",
    "Filter:": "筛选:",
    "Attach": "附加",
    "note:": "记录:",
    "Curses": "诅咒",
    "Body": "身体",
    "when": "当",
    "Praise": "表扬",
    "Only note": "仅记录",
    "Scold": "责备",
    "Name": "名称",
    "Note": "笔记",
    "room": "房间",
    "Rules": "规则",
    "Items": "物品",
    "Normal": "普通",
    "Limited": "受限制的",
    "Blocked": "被阻挡的",
    "Clothing": "服装",
    "Relationships": "人际关系",
    "room named": "房间名字",
    "Filter name:": "筛选名称:",
    "Member number": "成员编号",
    "room with role": "具有角色的房间",
    "Timer disabled": "定时器已禁用",
    "room with member": "有成员的房间",
    "Enforce this rule": "执行此规则",
    "Rule trigger conditions:": "规则触发条件:",
    "Please select a member.": "请选择一位成员.",
    "Curse trigger conditions:": "诅咒触发条件:",
    "Timer disabled by default": "定时器默认禁用",
    "Remove the item when the curse": "诅咒时移除物品",
    "Set to global rules configuration": "设置为全局规则配置",
    "Set to global curses configuration": "设置为全局诅咒配置",
    "Example: which rope tie is used": "示例: 使用了哪种绳索绑法",
    "Also curse the item's configuration": "同时对物品的配置施加诅咒",
    "This rule is active and can trigger": "此规则处于激活的状态并且可以触发",
    "This curse is active and can trigger": "此诅咒处于激活状态并且可以触发",
    "triggering - does not remove locked items": "触发 - 不会移除锁定的物品",
    "becomes inactive, removed, or is no longer": "变得不活跃、被移除或不再存在",
    "Note: Settings are applied to new curses and all existing ones set to the global config.":
        "注意: 这些设置适用于新的诅咒, 以及所有已设置为全局配置的现有诅咒",
    "- View / Edit the 'Miscellaneous' curse -": "- 查看/编辑 '杂项'诅咒 -",
    "- View / Edit the global curses configuration -": "- 查看/编辑 全局诅咒配置 -",
    '- Commands: Description of the command: "Eyes" -': '- 指令描述: "眼睛" -',
    '- Commands: Description of the command: "Mouth" -': '- 指令描述: "嘴巴" -',
    '- Commands: Description of the command: "Arms" -': '- 指令描述: "手臂" -',
    '- Commands: Description of the command: "Legs" -': '- 指令描述: "腿" -',
    '- Commands: Description of the command: "Allfours" -': '- 指令描述: "四肢着地" -',
    '- Commands: Description of the command: "Go and wait" -': '- 指令描述: "去等待" -',
    '- Commands: Description of the command: "Send to cell" -': '- 指令描述: "送进监狱" -',
    '- Commands: Description of the command: "Send to asylum" -': '- 指令描述: "送进收容所" -',
    '- Commands: Description of the command: "Deposit all keys" -': '- 指令描述: "没收所有钥匙" -',
    '- Commands: Description of the command: "Show remaining time" -': '- 指令描述: "显示剩余时间" -',
    '- Commands: Description of the command: "Send to serve drinks" -': '- 指令描述: "送去招待饮料" -',
    '- Commands: Description of the command: "Manipulate the arousal meter" -': '- 指令描述: "操纵高潮条" -',
    '- Commands: Description of the command: "Emoticon" -': '- 指令描述: "表情符号" -',
    '- Commands: Description of the command: "Forced say" -': '- 指令描述: "强制说" -',
    '- Commands: Description of the command: "Say" -': '- 指令描述: "说" -',
    '- Commands: Description of the command: "Typing task" -': '- 指令描述: "输入任务" -',
    '- Commands: Description of the command: "Forced typing task" -': '- 指令描述: "强制输入任务" -',
    "- Global: Enable/Disable BCX's modules -": "- 全局: 启用/禁用BCX的模块 -",
    "Warning: Disabling a module will reset all its settings and stored data!": "警告: 禁用模块将重置其所有设置和存储的数据!",
    "Authority module permissions (continued)": "权限模块权限 (延续)",
    "Behaviour Log module permissions": "行为日志模块权限",
    "Behaviour Log module permissions (continued)": "行为日志模块权限 (延续)",
    "Curses module permissions": "诅咒模块权限",
    "Curses module permissions (continued)": "诅咒模块权限 (延续)",
    "Rules module permissions": "规则模块权限",
    "Commands module permissions": "指令模块权限",
    "Relationships module permissions": "关系模块权限",
    "Export-Import module permissions": "导出-导入 模块权限",
    "Miscellaneous module permissions": "其他模块权限",
    "Restore previous value when rule ends": "规则结束时恢复之前的值",
    "Behaviour log entry when rule is violated": "违反规则时记录到行为日志",
    "Global": "全局",
    "Authority": "权限",
    "Export-Import": "导入导出",
    "Miscellaneous": "杂项",
    "For saying 'thank you' with a tip": "用于赞助支持",
    "Open changelog on GitHub": "在 GitHub 上打开更新日志",
    "Open invite to BCX Discord server": "打开 BCX Discord服务器邀请",
    "Show the BCX tutorial again": "再次显示 BCX教程",
    "Close tutorial": "关闭教程",
    "Instant Messenger": "即时消息",
    'Your initially selected BCX preset was: "Dominant"': '你最初选择的BCX预设是: "支配者"',
    'Your initially selected BCX preset was: "Switch"': '你最初选择的BCX预设是: "转换者"',
    'Your initially selected BCX preset was: "Submissive"': '你最初选择的BCX预设是: "服从者"',
    'Your initially selected BCX preset was: "Slave"': '你最初选择的BCX预设是: "奴隶"',
    "Manage BCX modules": "管理 BCX模块",
    "Clear all BCX data": "清除所有 BCX数据",
    "Enable/Disable individual modules": "启用/禁用 单个模块",
    "Emergency reset of BCX": "紧急重置BCX",
    "Confirm": "确认",
    "Cancel": "取消",
    "BCX main menu": "BCX 主菜单",
    "Add as owner": "添加为所有者",
    "Add as mistress": "添加为女主人",
    "Clubowner": "俱乐部主人",
    "Owner": "所有者",
    "Lover": "恋人",
    "Mistress": "女主人",
    "Whitelist": "白名单",
    "Friend": "朋友",
    "Public": "公开",
    "Configure the role-based BCX permissions": "配置基于角色的 BCX 权限",
    "Select member number from list": "从列表中选择成员编号",
    "You - either top or bottom of the hierarchy": "你 - 可以是层次结构的顶部或底部",
    "Your owner, visible on your character profile": "你的所有者,在你的角色资料中可见",
    'Any character, added to the list on the left as "Owner"': '任何角色,添加到左侧列表中作为 "所有者"',
    "Any of your lovers, visible on your character profile": "你的任何恋人,在你的角色资料中可见",
    'Any character, added to the list on the left as "Mistress"': '任何角色,添加到左侧列表中作为 "女主人"',
    "Anyone you have white-listed": "你白名单中的任何人",
    "Anyone you have friend-listed": "你好友名单中的任何人",
    "Anyone, who can use items on you": "任何可以在你身上使用物品的人",
    "Allow forbidding self access": "允许禁止自己访问",
    "Allow granting Mistress status": "允许授予女主人身份",
    "Allow granting Owner status": "允许授予所有者身份",
    "Allow granting self access": "允许授予自己访问权限",
    "Allow lowest access modification": "允许最低访问权限修改",
    "Previous screen": "上一页",
    "Allow revoking Mistress status": "允许撤销女主人身份",
    "Allow revoking Owner status": "允许撤销所有者身份",
    "Allow viewing list of owners/mistresses": "允许查看所有者/女主人列表",
    "Allow deleting log entries": "允许删除日志条目",
    "Allow to attach notes to the body": "允许附加注释到身体上",
    "Allow to configure what is logged": "允许配置日志记录的内容",
    "Allow to praise or scold": "允许表扬或责备",
    "Allow to see normal log entries": "允许查看正常的日志条目",
    "Allow to see protected log entries": "允许查看受保护的日志内容",
    "Allow changing colors of cursed objects": "允许更改被诅咒物品的颜色",
    "Allow to view who added the curse originally": "允许查看最初添加诅咒的人",
    "Allows editing the global curses configuration": "允许编辑全局诅咒配置",
    "Allows handling curses on limited object slots": "允许在限制的物体槽上处理诅咒",
    "Allows handling curses on non-limited object slots": "允许在非限制的物体槽上处理诅咒",
    "Allows to limit/block individual curse object slots": "允许限制/阻止单个诅咒对象槽",
    "Allow to view who added the rule originally": "允许查看最初添加规则的人",
    "Allows controlling limited rules": "允许控制限制的规则",
    "Allows controlling non-limited rules": "允许控制非限制的规则",
    "Allows editing the global rules configuration": "允许编辑全局规则配置",
    "Allows to limit/block specific rules": "允许限制/阻止特定规则",
    "Allows controlling limited commands": "允许控制限制的指令",
    "Allows controlling non-limited commands": "允许控制非限制的指令",
    "Allows to limit/block specific commands": "允许限制/阻止特定指令",
    "Allow changing relationship config for herself": "允许更改自己的关系配置",
    "Allow changing relationship config for others": "允许更改别人的关系配置",
    "Allow viewing others in relationship list": "允许查看关系列表中的别人",
    "Allow exporting BCX module configurations": "允许导出 BCX 模块配置",
    "Allow importing items using wardrobe": "允许使用衣柜导入物品",
    "Allow using the allowactivities command on this player": "允许在此玩家上使用 allowactivities 命令",
    '- Authority: Changing minimum access to permission "Allows controlling limited commands" -':
        '- 权限: 更改对权限 "允许控制限制的指令" 的最小访问权限',
    "Info: Currently set role: Owner → Newly selected role: Owner":
        "信息: 当前设置的角色: 所有者 → 新选择的角色: 所有者",
    "This player's owner, visible on their character profile": "这个玩家的所有者,可在他们的角色资料中看到",
    "This player - either top or bottom of the hierarchy": "这个玩家 - 可能是层级的顶端或底端",
    "Any lover of this player, visible on their profile": "这个玩家的任何恋人,在他们的资料中可见",
    "Anyone this player has white-listed": "任何已加入白名单的玩家",
    "Anyone this player has friend-listed": "任何已加入好友列表的玩家",
    "Anyone, who can use items on this player": "任何可以在这个玩家身上使用物品的玩家",
    "You have no permission to use this": "您没有使用此功能的权限",
    "Skip tutorial": "跳过教程",
    "<< Back to the tutorial": "<< 返回教程",
    '- Authority: Changing minimum access to permission "Allow forbidding self access" -':
        '- 权限: 更改对权限 "允许禁止自我访问" 的最小访问权限',
    '- Authority: Changing minimum access to permission "Allows editing the global curses configuration" -':
        '- 权限: 更改对权限 "允许编辑全局诅咒配置" 的最小访问权限',
    "The log has been cleared": "日志已被清除",
    "Configure logging": "配置日志记录",
    "Ability to see attached notes": "能够查看附加的备注",
    "Yes": "是",
    "Log changes in logging configuration": "记录日志配置的更改",
    "Protected": "受保护的",
    "Log changes in permission settings": "记录权限设置的更改",
    "Log deleted log entries": "记录删除的日志条目",
    "Log each addition, removal or change of rules": "记录每个规则的添加、移除或更改",
    "No": "否",
    "Log each application, removal or change of curses": "记录每个诅咒的应用、移除或更改",
    "Delete all log entries": "删除所有日志条目",
    "Log each change in relationships module": "记录关系模块的每次更改",
    "Log each change of commands limit": "记录命令限制的每次更改",
    "Log each single orgasm": "记录每一次的高潮",
    "Log every rule violation": "记录每一次违规",
    "Log every time a triggered curse reapplies an item": "记录每一次触发的诅咒重新应用物品",
    "Log getting or losing a BCX owner/mistress": "记录每一次增加或删除 BCX 所有者/女主人",
    "Log praising or scolding behavior": "记录赞扬或责备的行为",
    "Log which private rooms are entered": "记录进入哪些私人房间",
    "Log which public rooms are entered": "记录进入哪些公开房间",
    "Back": "返回",
    "ALL": "全部",
    "Activate all": "全部激活",
    "A. only": "仅激活",
    "Deactivate all": "全部停用",
    "D. only": "仅停用",
    "Change global rules config": "更改全局规则配置",
    "Remaining duration of the curse": "诅咒的剩余持续时间",
    "Add new rule": "添加新规则",
    "Existing rules set to global rules config are also changed": "全局规则配置中的现有规则也将被更改",
    "...from the list of yet unestablished rules": "......从尚未建立的规则列表中",
    "Switch all added rules to active": "将所有已添加规则切换为激活状态",
    "Activate only global config rules": "仅激活全局配置规则",
    "Deactivate only global config rules": "仅停用全局配置规则",
    "Switch all added rules to inactive": "将所有已添加规则切换为非激活状态",
    "Restrict entering rooms (only allow entering specific ones)": "限制进入房间(仅允许进入特定房间)",
    "Prevent leaving the room (while defined roles are inside)": "防止离开房间(当指定的角色在房间内时)",
    "Forbid tying up others (either everybody or only more dominant characters)":
        "禁止捆绑他人(可以是所有人或仅更占主导地位的角色)",
    "Prevent blacklisting (and ghosting of the defined roles)": "防止黑名单(和指定角色的幽灵化)",
    "Prevent whitelisting (of roles 'friend' or 'public')": "防止白名单('朋友'或'公共'角色)",
    "Forbid the antiblind command (BCX's .antiblind command)": "禁止反盲命令(BCX的 .antiblind 指令)",
    "Forbid changing difficulty (multiplayer difficulty preference)": "禁止更改难度(多人游戏的难度偏好)",
    "Prevent usage of all activities (any action buttons such as kissing or groping)":
        "防止使用所有活动(如亲吻或触摸等任何动作按钮)",
    "Forbid mainhall maid services (to get out of any restraints)": "禁止主厅女仆服务(以摆脱任何约束)",
    "Forbid the action command (BCX's .action/.a chat command)": "禁止行动指令(BCX的 .action/.a 聊天指令)",
    "Forbid looking at room admin UI (while blindfolded)": "禁止查看房间管理UI(戴眼罩时)",
    "Forbid using GGTS (training by GGTS is forbidden)": "禁止使用GGTS(GGTS的培训是禁止的)",
    "Prevent working as club slave (the task from the mistress room)": "防止成为俱乐部奴隶(女王室的任务)",
    "Prevent using items of others (items not bought)": "防止使用他人的物品(未购买的物品)",
    "Force-hide UI elements (e.g., icons, bars, or names)": "强制隐藏UI元素(例如图标、条形、或名称)",
    "Control ability to orgasm (adjustable: only-edge, only-ruin, no-resist)":
        "控制达到性高潮的能力(可调节: 仅限边缘,仅限毁灭,无抵抗)",
    "Secret orgasm progress (unable to see the own arousal meter)": "秘密性高潮进度(无法看到自己的高潮条)",
    "Room admin transfer (give admin to defined roles)": "房间管理员转让(将管理员权限赋予指定角色)",
    "Limit bound admin power (restrict room admin powers while restrained)":
        "限制被束缚玩家的管理员权限(在被束缚时限制房间管理员权限)",
    "Always carry a suitcase (from the kidnappers league multiplayer game)": "始终携带手提箱(来自绑匪联盟多人游戏)",
    "Hide online friends if blind (also preventing beeps from the friendlist - exceptions settable)":
        "如果失明,则隐藏在线好友(同时阻止来自好友列表的提示声音 - 可设置例外)",
    "Force 'Prevent random NPC events' (from BCX's Misc module)": "强制 '阻止随机NPC事件'(来自BCX的Misc模块)",
    "Forbid club owner changes (getting or leaving owner)": "禁止更改俱乐部主人(获得或离开主人)",
    "Forbid taking new submissives (by offering them an ownership trial)":
        "禁止接收新的顺从者(通过为他们提供所有权试用期)",
    "Allow specific sounds only (such as an animal sound)": "只允许特定的声音(如动物声音)",
    "Garble whispers while gagged (same as normal messages)": "在堵嘴时混肴私语(与普通消息相同)",
    "Block OOC chat while gagged (no more misuse of OOC for normal chatting while gagged)":
        "在被堵嘴时阻止OOC聊天(防止在被堵嘴时滥用OOC进行正常聊天)",
    "Block OOC chat (blocks use of OOC in messages)": "阻止OOC聊天(阻止在消息中使用OOC)",
    "Doll talk (allows only short sentences with simple words)": "娃娃聊天(只允许简单词汇的短句)",
    "Forbid saying certain words in chat (based on a configurable blacklist)":
        "禁止在聊天中说某些词(基于可配置的黑名单)",
    "Forbid saying certain words in emotes (based on a configurable blacklist)":
        "禁止在表情中说某些词(基于可配置的黑名单)",
    "Forbid talking openly (in a chat room)": "禁止在聊天室里公开谈话",
    "Limit talking openly (only allow a set number of chat messages per minute)":
        "限制公开聊天(每分钟只允许设定数量的聊天消息)",
    "Forbid using emotes (in a chat room)": "禁止在聊天室使用表情",
    "Limit using emotes (only allow a set number of emotes per minute)": "限制使用表情(每分钟只允许设定数量的表情)",
    "Restrict sending whispers (except to defined roles)": "限制发送私语(除了指定的角色)",
    "Restrict receiving whispers (except from defined roles)": "限制接收私语(除了指定的角色)",
    "Restrict sending beep messages (except to selected members)": "限制发送私聊/蜂鸣消息(仅限于选定的成员)",
    "Restrict receiving beeps (and beep messages, except from selected members)":
        "限制接收私聊/蜂鸣声(和蜂鸣消息,除非来自选定的成员)",
    "Order to greet club (when entering it through the login portal)": "命令打招呼俱乐部(通过登录门户进入时)",
    "Forbid the antigarble option (BCX's .antigarble command)": "禁止防乱码选项(BCX的 .antigarble 命令)",
    "Force to retype (if sending a message in chat is rejected by BCX due to a rule violation)":
        "强制重新输入(如果违反规则而BCX将拒绝在聊天中发送消息)",
    "Order to greet room (with a settable sentence when entering it newly)":
        "命令向房间打招呼(新进入房间时用设置的句子打招呼)",
    "Greet new guests (when they join the current room)": "欢迎新客人(当他们加入当前房间时)",
    "Establish mandatory words (of which at least one needs to always be included when speaking)":
        "建立强制词汇(说话时必须包含至少一个)",
    "Establish mandatory words in emotes (of which at least one needs to always be included)":
        "在表情中建立强制词汇(发送表情时必须包含至少一个)",
    "Partial hearing (of muffled speech - random & word list based)": "部分听力(受到沉闷言语的影响 - 基于随机和词汇表)",
    "Track rule effect time (counts the time this rule's trigger conditions were fulfilled)":
        "追踪规则生效时间(计算此规则的触发条件得到满足的时间)",
    "Log money changes (spending and/or getting money)": "记录金钱变动(支出和/或获得金钱)",
    "Edit rules permissions": "编辑规则权限",
    "Leave permission mode": "离开权限修改模式",
    "Change global curses config": "更改全局诅咒配置",
    "Add new curse": "添加新诅咒",
    "Lift all curses": "解除所有诅咒",
    "Place new curses on body, items or clothes": "在身体、物品或衣物上施加新的诅咒",
    "Remove all curses on body, items or clothes": "移除身体、物品或衣物上的所有诅咒",
    "Existing curses set to global curses config are also changed": "全局诅咒配置中已存在的诅咒也会被更改",
    "Activate only global config curses": "仅激活全局配置的诅咒",
    "Switch all added curses to inactive": "将所有已添加诅咒切换为非活动状态",
    "Switch all added curses to active": "将所有已添加诅咒切换为活动状态",
    "Deactivate only global config curses": "仅停用全局配置的诅咒",
    "Curse occupied": "诅咒已占用",
    "Curse all": "全部诅咒",
    "Lower Leg": "小腿",
    "Upper Leg": "大腿",
    "Nipple Piercing": "乳头穿孔",
    "Collar Addon": "项圈附加件",
    "Collar Restraint": "项圈拘束",
    "Mouth (1)": "嘴巴 (1)",
    "Mouth (2)": "嘴巴 (2)",
    "Mouth (3)": "嘴巴 (3)",
    "Hood": "头套",
    "Devices": "设备",
    "General Addon": "通用附属物",
    "Feet": "脚",
    "Ears Accessory": "耳朵饰品",
    "Nothing": "无",
    "Curse all occupied slots at once": "一次性诅咒所有已占用的插槽",
    "Curse all slots at once": "一次性诅咒所有插槽",
    "Edit curse slot permissions": "编辑诅咒插槽权限",
    "Character Height": "角色身高",
    "Mouth Style": "嘴巴样式",
    "Pussy Style": "阴部样式",
    "Toggle alphabetical sorting": "切换字母排序",
    "Toggle availability-based sorting": "切换基于可用性的排序",
    "You don't have permission to use this rule": "您没有使用此规则的权限",
    "Show remaining time (Remaining time of keyhold, asylum stay, or GGTS training)":
        "显示剩余时间 (持钥匙时间、收容所逗留时间或 GGTS 训练)",
    "Edit commands permissions": "编辑命令权限",
    "Add": "添加",
    "Authority - Permissions": "权限 - 权限",
    "Behaviour Log - Configuration": "行为日志 - 配置",
    "Curses - Limits": "诅咒 - 限制",
    "Rules - Limits": "规则 - 限制",
    "Commands - Limits": "指令 - 限制",
    "Export": "导出",
    "Import": "导入",
    "Export current config": "导出当前配置",
    "Try to import a previously exported config": "尝试导入先前导出的配置",
    "Enable timer": "启用定时器",
    "Always in effect": "始终生效",
    "in": "在",
    "public": "公共",
    "-1d": "-1天",
    "-1h": "-1小时",
    "-5m": "-5分钟",
    "+5m": "+5分钟",
    "+1h": "+1小时",
    "+1d": "+1天",
    "Removes rule instead of only deactivating it": "删除规则而不仅仅是停用它",
    "Overwrites current trigger conditions": "覆盖当前触发条件",
    "All selected below": "下面全部选中",
    "not in": "不在",
    "private": "私有",
    "[unknown],": "[未知],",
    "Mistress ↑": "女主人 ↑",
    "Whitelist ↑": "白名单 ↑",
    "Friend ↑": "朋友 ↑",
    "Public ↑": "公共 ↑",
    "Owner ↑": "所有者 ↑",
    "Lover ↑": "恋人 ↑",
    "Go back without saving": "返回而不保存",
    "Save all changes and go back": "保存所有更改并返回",
    "Many": "许多",
    "Default": "默认",
    "Exclude body parts": "排除身体部位",
    "Include items/restraints": "包括物品/限制",
    "Copied to clipboard!": "已复制到剪贴板!",
    "Clothes": "衣服",
    "Select individually": "单独选择",
    "Cosplay items": "角色扮演道具",
    "Restraints/items": "限制/物品",
    "Collar": "项圈",
    "Piercings": "穿孔",
    "Locks": "锁",
    "Color help": "颜色帮助",
    "<<< Back": "<<< 返回",
    "[EMPTY]": "[空]",
    "Global configuration is not possible on others": "无法在其他角色上进行全局配置",
    "Please select the new lowest role that should still have this permission.":
        "请选择新的最低角色权限等级以保持此权限.",
    "All roles to the left of the selected one will also automatically get access.":
        "所选角色左侧的所有角色也将自动获得访问权限.",
    "WARNING: If you confirm, all permitted roles can remove your access to this and all other permissions!":
        "警告: 如果您确认,所有被允许的角色都可以撤销您对此和所有其他权限的访问权限!",
    '- Authority: Changing minimum access to permission "Allow granting Mistress status" -':
        '- 权限: 更改对 "允许授予女主身份" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow granting Owner status" -':
        '- 权限: 更改对 "允许授予所有者身份" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow granting self access" -':
        '- 权限: 更改对 "允许授予自己访问权限" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow lowest access modification" -':
        '- 权限: 更改对 "允许最低访问级别修改" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow revoking Mistress status" -':
        '- 权限: 更改对 "允许撤销女主身份" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow revoking Owner status" -':
        '- 权限: 更改对 "允许撤销所有者身份" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow viewing list of owners/mistresses" -':
        '- 权限: 更改对 "允许查看所有者/女主列表" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow deleting log entries" -':
        '- 权限: 更改对 "允许删除日志条目" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow to attach notes to the body" -':
        '- 权限: 更改对 "允许在身体上添加注释" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow to configure what is logged" -':
        '- 权限: 更改对 "允许配置记录的内容" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow to praise or scold" -':
        '- 权限: 更改对 "允许表扬或责备" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow to see normal log entries" -':
        '- 权限: 更改对 "允许查看普通日志条目" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow to see protected log entries" -':
        '- 权限: 更改对 "允许查看受保护的日志条目" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow changing colors of cursed objects" -':
        '- 权限: 更改对 "允许更改被诅咒物品的颜色" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow to view who added the curse originally" -':
        '- 权限: 更改对 "允许查看最初添加诅咒的人" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allows handling curses on limited object slots" -':
        '- 权限: 更改对 "允许在限制的对象槽上处理诅咒" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allows handling curses on non-limited object slots" -':
        '- 权限: 更改对 "允许在非限制的对象槽上处理诅咒" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allows to limit/block individual curse object slots" -':
        '- 权限: 更改对 "允许限制/阻止个别诅咒对象槽" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow to view who added the rule originally" -':
        '- 权限: 更改对 "允许查看最初添加规则的人" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allows controlling limited rules" -':
        '- 权限: 更改对 "允许控制限制规则" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allows controlling non-limited rules" -':
        '- 权限: 更改对 "允许控制非限制规则" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allows editing the global rules configuration" -':
        '- 权限: 更改对 "允许编辑全局规则配置" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allows to limit/block specific rules" -':
        '- 权限: 更改对 "允许限制/阻止特定规则" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allows controlling non-limited commands" -':
        '- 权限: 更改对 "允许控制非限制命令" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allows to limit/block specific commands" -':
        '- 权限: 更改对 "允许限制/阻止特定命令" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow changing relationship config for herself" -':
        '- 权限: 更改对 "允许为自己更改关系配置" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow changing relationship config for others" -':
        '- 权限: 更改对 "允许为别人更改关系配置" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow viewing others in relationship list" -':
        '- 权限: 更改对 "允许查看别人的关系列表" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow exporting BCX module configurations" -':
        '- 权限: 更改对 "允许导出BCX模块配置" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow importing items using wardrobe" -':
        '- 权限: 更改对 "允许使用衣柜导入物品" 权限的最低访问级别 -',
    '- Authority: Changing minimum access to permission "Allow using the allowactivities command on this player" -':
        '- 权限: 更改对 "允许在此玩家上使用 allowactivities 命令" 权限的最低访问级别 -',
    "Forbid using remotes on others": "禁止对别人使用遥控器",
    "Forbid using remotes on self": "禁止对自己使用遥控器",
    "Forbid using keys on others": "禁止对别人使用遥控器",
    "Forbid using keys on self": "禁止对自己使用钥匙",
    "Forbid tying up others": "禁止捆绑别人",
    "Prevent blacklisting": "禁止增加黑名单",
    "Forbid freeing self": "禁止自己解开自己的拘束",
    "Forbid creating new rooms": "禁止创建新房间",
    "Restrict allowed body poses": "限制允许的身体姿势",
    "Forbid using locks on self": "禁止对自己使用锁",
    "Forbid picking locks on self": "禁止自己的撬自己的锁",
    "Forbid wardrobe use on self": "禁止更换自己的服装",
    "Forbid picking locks on others": "禁止撬别人的锁",
    "Forbid using locks on others": "禁止对别人使用锁",
    "Forbid wardrobe use on others": "禁止更换别人的服装",
    "Restrict entering rooms": "限制进入房间",
    "Prevent leaving the room": "禁止离开房间",
    "Forbid the antiblind command": "禁止使用反盲指令",
    "Prevent usage of all activities": "禁止使用所有交互动作",
    "Forbid mainhall maid services": "禁止大厅女仆的解绑服务",
    "Forbid changing difficulty": "禁止改变难度",
    "Prevent whitelisting": "禁止增加白名单",
    "Forbid the action command": "禁止bcx的动作指令(.a)",
    "Prevent using BCX permissions": "禁止使用 BCX 权限",
    "Forbid looking at room admin UI": "禁止查看房间管理界面",
    "Forbid using GGTS": "禁止使用 GGTS",
    "Prevent working as club slave": "禁止成为俱乐部的奴隶",
    "Prevent using items of others": "禁止使用别人的物品",
    "Prevent changing own emoticon": "禁止更改自己的表情符号",
    "Force-hide UI elements": "强制隐藏 UI 元素",
    "Sensory deprivation: Sound": "感官剥夺: 听觉",
    "Hearing whitelist": "听觉白名单",
    "Sensory deprivation: Sight": "感官剥夺: 视觉",
    "Seeing whitelist": "视觉白名单",
    "Fully blind when eyes are closed": "闭眼时时完全看不见",
    "Field of vision for eyes": "眼睛的视野",
    "Fully blind when blindfolded": "蒙眼时完全看不见",
    "Always leave rooms slowly": "总是缓慢离开房间",
    "Set slowed leave time": "设置缓慢离开的时间",
    "Control ability to orgasm": "控制高潮",
    "Secret orgasm progress": "对自己隐藏高潮条",
    "Room admin transfer": "转移房间管理权限",
    "Limit bound admin power": "限制被束缚时管理员的权限",
    "Control profile online description": "控制bio/在线个人简介",
    "Control nickname": "控制昵称",
    "Always carry a suitcase": "总是携带一个手提箱",
    "Restrict being leashed by others": "限制被别人牵引",
    "Hide online friends if blind": "失明时隐藏好友列表",
    "Ready to be summoned": "准备好被召唤",
    "Allow changing the whole appearance": "允许改变整体外观",
    "Item permission": "物品权限",
    "Locks on you can't be picked": "锁在你身上无法被撬开",
    "Cannot enter single-player rooms when restrained": "当被束缚时不能进入单人房间",
    "Allow safeword use": "是否允许安全词",
    "Arousal meter": "高潮条",
    "Block advanced vibrator modes": "屏蔽高级震动器模式",
    "Arousal speech stuttering": "兴奋时口吃",
    "Show AFK bubble": "显示 AFK 气泡",
    "Allow others to alter your whole appearance": "允许别人改变你的整体外观",
    "Prevent others from changing cosplay items": "禁止别人更换你的角色扮演道具",
    "Sensory deprivation setting": "感官剥夺设置",
    "Hide non-adjacent players while partially blind": "在部分失明时隐藏非相邻玩家",
    "Garble chatroom names and descriptions while blind": "失明时混淆聊天室的名称和描述",
    "Keep all restraints when relogging": "重新登录时保存所有束缚和道具",
    "Players can drag you to rooms when leashed": "当被牵住时, 玩家可以把你拖到其他房间",
    "Return to chatrooms on relog": "重新登录时返回聊天室",
    "Events while plugged or vibed": "插着或振动时发生事件",
    "Allow item tint effects": "允许物品染色效果",
    "Allow item blur effects": "允许物品模糊效果",
    "Flip room vertically when upside-down": "倒立时房间垂直翻转",
    "Prevent random NPC events": "阻止随机 NPC 事件",
    "Forbid club owner changes": "禁止更换俱乐部主人",
    "Forbid getting new lovers": "禁止交新的恋人",
    "Forbid breaking up with lovers": "禁止与恋人分手",
    "Forbid taking new submissives": "禁止接收新的顺从者",
    "Forbid disowning submissives": "禁止放弃顺从者",
    "Allow specific sounds only": "仅允许特定声音",
    "Garble whispers while gagged": "被堵嘴时混淆耳语",
    "Block OOC chat while gagged": "被堵嘴时阻止 OOC 聊天",
    "Block OOC chat": "阻止 OOC 聊天",
    "Doll talk": "玩偶言语",
    "Forbid saying certain words in chat": "禁止在公屏和私语中说某些词",
    "Forbid saying certain words in emotes": "禁止在表情中说某些词",
    "Forbid talking openly": "禁止公屏聊天",
    "Limit talking openly": "限制公屏聊天频率",
    "Forbid using emotes": "禁止使用表情(*)",
    "Limit using emotes": "限制使用表情(*)频率",
    "Restrict sending whispers": "限制发送耳语",
    "Restrict receiving whispers": "限制接收耳语",
    "Restrict sending beep messages": "限制发送私聊/蜂鸣消息",
    "Restrict receiving beeps": "限制接收私聊/蜂鸣",
    "Order to greet club": "登录时自动发私聊问候",
    "Forbid the antigarble option": "禁止反语言混淆选项",
    "Force to retype": "强制重新输入",
    "Order to greet room": "进房间时自动发送的问候语",
    "Greet new guests": "问候新客人",
    "Enforce faltering speech": "强制断句说话",
    "Establish mandatory words": "建立必用的词汇",
    "Establish mandatory words in emotes": "在表情中建立必用的词汇",
    "Partial hearing": "部分听觉",
    "Force garbled speech": "强制失真聊天",
    "Forbid going afk": "禁止 AFK",
    "Track rule effect time": "追踪规则生效时间",
    "Listen to my voice": "听我的声音(洗脑语音)",
    "Log money changes": "记录货币变动",
    "Track BCX activation": "追踪 BCX 激活情况",
    "Miscellaneous module configuration is not possible on others": "无法在他人身上进行杂项模块配置",
    "Module is deactivated": "模块已停用",
    "Members numbers allowed to summon:": "允许召唤的成员编号:",
    "The text used for summoning:": "用于召唤的文本:",
    "Time in seconds before enforcing summon:": "强制召唤前的时间(秒):",
    "Minimum role that is allowed to leash:": "允许牵引的最低角色:",
    "Members numbers still heard while hearing impaired:": "听觉受损时仍然可听到的成员编号:",
    "Also understand if those are speech impaired": "是否同时理解言语障碍",
    "New leave time in seconds:": "新的离开时间(秒):",
    "Set this player's nickname:": "设置此玩家的昵称:",
    "Restore the previous nickname at rule end": "在规则结束时恢复先前的昵称",
    "Set the allowed sounds:": "设置允许的声音:",
    "All forbidden words:": "所有禁止的词语:",
    "Amount of minutes, before being considered inactive:": "被视为不活跃之前的分钟数:",
    "Also log getting money": "也记录获取金钱",
    "Still allow unlocking owner locks or items": "仍然允许解锁主人锁或物品",
    "Still allow unlocking lover locks or items": "仍然允许解锁恋人锁或物品",
    "Minimum role able to request counted time:": "能够请求计时的最低角色:",
    "The sentences that will be shown at random:": "将随机显示的句子:",
    "Frequency of a sentence being shown (in minutes):": "句子显示的频率(分钟):",
    "Everyone, no exceptions": "所有人,无例外",
    "BCX: Rule changed your 'Item permission' setting": "BCX: 规则更改了您的'物品权限'设置",
    "Everyone, except blacklist": "所有人,除了黑名单",
    "Owner, Lovers, whitelist & Dominants": "主人,恋人,白名单和支配者",
    "Owner, Lovers and whitelist only": "仅主人,恋人和白名单",
    "BCX: Rule changed your 'Locks on you can't be picked' setting": "BCX: 规则更改了您的'不能撬开您身上的锁'设置",
    "Hearing impairment:": "听觉受损:",
    "Light": "轻度",
    "Medium": "中度",
    "Heavy": "重度",
    "Eyesight impairment:": "视觉受损:",
    "Player sees the effect also on herself": "玩家也能在自己身上看到效果",
    "Hide names and icons during the effect": "在效果期间隐藏名字和图标",
    "Orgasm attempts will be fixed to:": "尝试高潮将被固定为:",
    "Edge": "边缘",
    "Ruin": "毁灭",
    "Prevent resisting": "防止抵抗",
    "Minimum role that gets admin:": "获得管理员权限的最低角色:",
    "Player loses admin afterwards": "玩家在之后失去管理员权限",
    "Edit this player's profile description:": "编辑此玩家的个人描述:",
    "Members numbers that can always be seen:": "始终可见的成员编号:",
    "Mark poses as being allowed or forbidden:": "将姿势标记为允许或禁止:",
    "Only joining rooms with these names is allowed:": "只允许加入具有这些名称的房间:",
    "Minimum role preventing room leaving:": "阻止离开房间的最低角色:",
    "Favorite: Listed first in overview": "收藏: 在概览中首先列出",
    "Still allow removing low difficulty items": "仍然允许移除低难度物品",
    "Only forbid tying people with higher dominance": "仅禁止对更高支配值的玩家进行绑缚",
    "Minimum role forbidden to blacklist:": "被禁止添加到黑名单的最低角色:",
    "The level of forced garbling": "强制性的语音失真程度",
    "Words that can always be understood:": "始终可以理解的单词:",
    "Some words are randomly understood": "一些单词将随机理解",
    "Can also understand gagged persons": "也能理解被塞口球的玩家",
    "At least one of these words always needs to be used:": "这些单词中至少需要始终使用一个:",
    "Also affect whispered messages": "也影响私语消息",
    "Member numbers still allowed to send beeps:": "仍然允许发送蜂鸣消息的成员编号:",
    "Auto replies blocked sender with this:": "自动回复被屏蔽发件人使用此:",
    "Only in effect when unable to use hands": "仅在无法使用双手时生效",
    "Member numbers that will be greeted:": "将被问候的成员编号:",
    "The sentence that has to be used to greet any joined room:": "必须用于问候任何加入的房间的句子:",
    "Also forbid emote messages before greeting": "还禁止在问候之前发送表情消息",
    "The sentence that will be used to greet new guests:": "将用于问候新客人的句子:",
    "Usage blocked by BCX": "被BCX禁止使用",
    "Filter items": "过滤物品",
    "Select what shall be hidden:": "选择要隐藏的内容:",
    "Icons": "图标",
    "Also hide emoticons during the effect": "在生效期间也隐藏表情符号",
    "Icons/Bar": "图标/条",
    "Icons/Bar/Names": "图标/条/名称",
    "Minimum role that is allowed:": "允许的最低角色:",
    "Sexual activities - Activation": "性活动 - 激活",
    "Allow with a hybrid meter": "允许使用混合仪表",
    "Meter visibility": "仪表可见性",
    "Show arousal to everyone": "向所有人显示高潮条",
    "Show if they have access": "如果他们有权限则显示",
    "BCX: Rule changed your 'Arousal meter' setting": "BCX: 规则更改了你的'高潮条'设置",
    "Allow with a locked meter": "允许使用锁定的仪表",
    "Disable sexual activities": "禁用性活动",
    "Allow without a meter": "允许没有仪表",
    "Allow with a manual meter": "允许使用手动仪表",
    "Show to yourself only": "仅自己可见",
    "Speech stuttering": "语言结巴",
    "Aroused & vibrated": "激动和振动",
    "Never stutter": "永不结巴",
    "When you're aroused": "当你兴奋时",
    "When you're vibrated": "当你被振动时",
    "BCX: Rule changed your 'Show AFK bubble' setting": "BCX: 规则更改了你的'显示离开状态气泡'设置",
    "Disable examining when blind": "失明时禁用检查",
    "Hide others' messages": "隐藏他人的消息",
    "Hide names": "隐藏名称",
    "BCX: Rule changed your 'Sensory deprivation setting' setting": "BCX: 规则更改了你的'感官剥夺设置'设置",
    "Total": "总计",
    "Auto-remake rooms": "自动重新创建房间",
    "BCX: Rule changed your 'Return to chatrooms on relog' setting": "BCX: 规则更改了你的'重新登录时返回聊天室'设置",
    "BCX: Rule changed your 'Allow item blur effects' setting": "BCX: 规则更改了你的'允许物品模糊效果'设置",
    "BCX: Rule changed your 'Flip room vertically when upside-down' setting":
        "BCX: 规则更改了你的'倒置时垂直翻转房间'设置",
    "Max. character length of any word:": "任何单词的最大字符长度:",
    "Max. number of words per message:": "每条消息的最大单词数:",
    "Maximum allowed number of chat messages per minute (> 0):": "每分钟允许的最大聊天消息数 (> 0):",
    "Maximum allowed number of emotes per minute (> 0):": "每分钟允许的最大表情数 (> 0):",
    "Minimum role whispering is still allowed to:": "仍允许接收悄悄话的最低角色:",
    "Minimum role still allowed to send whisper:": "仍允许发送耳语的最低角色:",
    "Member numbers still allowed to be beeped:": "仍允许蜂鸣消息的玩家编号:",
    "BCX: You are not allowed to talk openly in chatrooms!": "BCX: 你不能在聊天室中公开说话!",
    "BCX: A BCX rule prevents you from using this while unable to see!": "BCX: 一个BCX规则阻止你在无法看到的情况下使用这个!",
    "Instant Messenger (Disabled by BCX)": "即时通讯(被BCX禁用)",
    "BCX: You are not allowed to use emotes in chatrooms!": "BCX: 不允许在聊天室使用表情!",
    "BCX: You are not allowed to change the emoticon!": "BCX: 不允许更改表情!",
    "Toggle Shared Crafts": "共享自制道具",
    "Modify layering priority": "修改图层优先级",
    "Adjust individual layers": "调整单独图层",
    "Set item priority": "设置物品优先级",
    "Choose clothing": "选择服装",
    "Choose body parts": "选择身体部位",
    "Choose cosplay items": "选择角色道具",
    "How does it work?": "它是如何操作的?",
    "If you are permitted, this screen enables you to view, add, or remove the BCX-only roles 'Owner' and 'Mistress', which expand the classic roles of BC such as Bondage Club's Owner and the Lovers. The hierarchy of all roles that can be used to set various things in BCX can be seen on the right. The higher up a role is, the more authority it has. For instance, if something applies or is permitted for a Mistress, it also always is for an Owner. Any number of Owners and Mistresses can be set. Check their current power over BCX with the button on the right.":
        "如果您获得许可, 此屏幕使您能够查看、添加或删除仅限 BCX 的角色“主人”和“女主人”, 这拓展了 BC 的经典角色, 如束缚俱乐部的主人和恋人.可用于在 BCX 中设置各种事项的所有角色的层级结构显示在右侧.角色位置越高, 其权限越大.例如, 如果某事适用于女主人或对其许可, 那么对主人也始终适用.可以设置任意数量的主人和女主人.使用右侧的按钮检查它们对 BCX 的当前权限.",
    "we are happy you are interested in our extension for the Bondage Club (BC) in which we invest a lot of our free time and love. If you have any questions, suggestions, or encounter any bugs, please feel free to get in touch with us on Discord. A button linking to it is in the main menu.":
        "我们很高兴您对我们为束缚俱乐部(BC)所做的扩展感兴趣, 我们在其中投入了大量的空闲时间和热爱.如果您有任何问题、建议或遇到任何错误, 请随时通过 Discord 与我们联系.主菜单中有一个指向它的按钮.",
    "The heart of BCX: Allows to configure the permissions to set up and use most of BCX. Default settings depend on the initial BCX setup preset selected. Self access is the checkbox next to every permission and the lowest access role is to its right. Example: If 'allow forbidding self access', 'allow granting self access', 'allow lowest access modification' have the checkbox removed and lowest role is 'Owner', then current and newly added BCX owners and the BC owner can get full control over any permissions they have access to. So careful with those three permissions!":
        "BCX 的核心：允许配置设置和使用 BCX 大部分内容的权限.默认设置取决于所选择的初始 BCX 设置预设.自访问是每个权限旁边的复选框, 最低访问角色在其右侧.例如：如果“允许禁止自访问”“允许授予自访问”“允许最低访问修改”的复选框被取消, 且最低角色是“主人”, 那么当前和新添加的 BCX 所有者以及 BC 所有者可以完全控制他们有权访问的任何权限.所以要小心这三个权限!",
    "This screen shows logs of important events. What is logged depends on the logging configuration, which can be viewed/edited via the button to the right. Log entries can have normal or protected visibility. Access to those as well as removing entries or the configuration is determined by the according authority module permission settings. The log can document the BCX's user's conduct, any rule violations, important changes made to BCX settings, curses or rules, and notes from other people.":
        "此界面展示重要事件的日志.所记录的内容取决于日志配置, 可通过右侧的按钮进行查看/编辑.日志条目可以有普通或受保护的可见性.对这些条目的访问以及条目的删除或配置由相应的权限模块权限设置决定.该日志可以记录 BCX 用户的行为、任何违规行为、对 BCX 设置的重要更改、诅咒或规则, 以及他人的注释.",
    "This screen determines what is logged in the behaviour log and what the visibility of each type of log messages is. 'Yes' means this log type has normal visibility, while 'protected' means only roles who have permission to view protected entries can view them. 'No' means that this log type is not logged at all. In the permission settings view of the authority module, the permissions of this log module can be configured.":
        "此界面决定了行为日志中记录的内容以及每种类型日志消息的可见性.“是”意味着此日志类型具有正常可见性, 而“受保护”意味着只有有权查看受保护条目的角色才能查看它们.“否”表示根本不记录此日志类型.在权限模块的权限设置视图中, 可以配置此日志模块的权限.",
    "This screen shows all active curses on the player, including many information, such as duration, if it is a cursed item/clothing/body slot or a blocked item or clothing slot that forces to stay unrestrained or naked there. Clicking on the button with the cog icon in the middle of each row moves you to a new screen that allows to configure the curse (if you have permission). When the cog icon has a blue aura, that means that the curse's conditions are the same as the global config. If permitted, you can remove single curses with the 'X' button.":
        "此界面展示了玩家身上所有生效的诅咒, 包含诸多信息, 比如持续时间、是被诅咒的物品/服装/身体槽位, 还是强制保持不受限制或赤裸的被封锁物品或服装槽位.点击每行中间带有齿轮图标的按钮, 会将您转到一个新的界面, 允许您配置该诅咒(如果您有权限).当齿轮图标带有蓝色光环时, 意味着该诅咒的条件与全局配置相同.如果允许, 您可以使用“X”按钮删除单个诅咒..",
    "The settings on this page are the global/default settings for all newly added curses. Changes to the trigger conditions are also applied to existing curses that are (still) set to global curses configuration, though. Exception is if a timer is set here. Such a timer only applies to newly created curses.":
        "此页面上的设置是所有新添加诅咒的全局/默认设置.对触发条件的更改也适用于(仍然)设置为全局诅咒配置的现有诅咒, 不过, 如果在此处设置了计时器则是个例外.这样的计时器仅适用于新创建的诅咒.",
    "Here, you can add a curse to any empty slot (white) which will keep it empty or on any worn item (gold) which will prevent removal. You add the curse by simply clicking the slot which then becomes purple to indicate that it is now cursed. Grey slots indicate that you have no access to them, due to them being blocked or due to your permission settings. Slots can be limited/blocked via the settings button on the very right. The screen has a second page for the character's body slots.":
        "在此, 您可以向任何空槽(白色)添加诅咒, 使其保持为空, 或者向任何已佩戴的物品(金色)添加诅咒, 使其无法被移除.您只需点击槽位即可添加诅咒, 随后该槽位会变为紫色, 表示已被诅咒.灰色槽位表示由于它们被封锁或您的权限设置, 您无法访问它们.可以通过最右侧的设置按钮来限制/封锁槽位.此屏幕针对角色的身体槽位还有第二页.",
    "This screen shows all active rules for the player, including many information, such as duration, the rule type and little status icons that show if the rule is enforced and/or transgressions are logged. Clicking on the button with the cog icon in the middle of each row moves you to a new screen that allows to configure the rule (if you have permission). When the cog icon has a blue aura, then that means that the rule's conditions are the same as the global config. If permitted, you can remove single rules with the 'X' button.":
        "此屏幕展示了玩家的所有生效规则, 包含诸多信息, 例如持续时间、规则类型以及显示规则是否正在执行和/或是否记录了违规行为的小状态图标.点击每行中间带有齿轮图标的按钮, 会将您转到一个新的屏幕, 允许您配置该规则(如果您有权限).当齿轮图标带有蓝色光环时, 意味着该规则的条件与全局配置相同.如果允许, 您可以使用“X”按钮删除单个规则.",
    "On this screen you can see the available commands for the player. Clicking on one shows a more detailed description of it. Greyed out commands indicate that you have no access to them due to being blocked or due to your permission settings. Commands can be limited/blocked via the settings button on the very right. Commands will be used in the chat room's chat by whispering them with a '!' before the command to another player. Note: SOME of the commands can also be used on yourself with a leading '.' instead of '!' (e.g. '.eyes close')":
        "在这个屏幕上, 您可以看到玩家可用的命令.点击其中一个命令会显示其更详细的描述.呈灰色的命令表示由于被阻止或权限设置, 您无法访问它们.可以通过最右侧的设置按钮来限制/封锁命令.在聊天室的聊天中, 通过在向其他玩家发送的命令前加上“!”来使用这些命令进行私语交流.注意：某些命令也可以在自己身上使用, 用“.”而不是“!”作为前缀(例如“.eyes close”)",
    "Here you can cycle commands between being not limited, limited and blocked. Blocked means no one can use this command, while limited means only roles that have the permission to use limited commands can trigger them in that chat. There is no need to save changes as they are instantly in effect.":
        "在这里, 您可以在“不受限制”“受限制”和“被阻止”之间切换命令.“被阻止”意味着无人能够使用此命令, 而“受限制”意味着只有拥有使用受限命令权限的角色才能在该聊天中触发它们.无需保存更改, 因为它们会立即生效.",
    "This screen lets you add custom nicknames for other club members. The set custom name replaces the added character's real name / BC-nickname in this player's chat, except within chat commands, which are considered OOC. You can also enforce the custom name so that the player is blocked from sending a chat message / whisper that use the character's name / BC-nickname while with her. The player cannot have multiple custom names set for a single character. A character who has a custom name set on this screen can always see their own set custom name in this list.":
        "此界面可让您为其他俱乐部成员添加自定义昵称.所设置的自定义名称会在该玩家的聊天中取代所添加角色的真实姓名/BC 昵称, 但在被视为脱离角色(OOC)的聊天命令中除外.您还可以强制使用自定义名称, 以阻止玩家发送使用该角色姓名/BC 昵称的聊天消息/私语.对于单个角色, 玩家不能设置多个自定义名称.在该屏幕上设置了自定义名称的角色始终可以在此列表中看到自己所设置的自定义名称.",
    "Please select the module feature you want to backup or import from a previous export. After storing the exported texts, you can later on use them again, e.g. for switching between cursed outfits or different rule sets. These exports are compatible between different BCX users and can be used by everyone with BCX who is permitted to make changes to the according module. For instance, if an owner has the permission to control limited AND non-limited rules on the sub, she is with that also allowed to import previously exported rules that are not blocked.":
        "请选择您想要备份或从先前的导出中导入的模块功能.在存储导出的文本之后, 您日后可以再次使用它们, 例如在受诅咒的服装之间切换或不同的规则集之间切换.这些导出在不同的 BCX 用户之间是兼容的, 并且可以由拥有更改相应模块权限的每个 BCX 用户使用.例如, 如果所有者有权控制子项的有限和非有限规则, 那么她也被允许导入先前未被阻止的导出规则.",
    "This screen offers various settings to configure your Bondage Club experience in general, such as enabling/disabling the typing indicator that shows other BCX users an icon when you are currently typing something to public chat or whispering something to only them. The cheats are only temporarily active as long as they are set; items that were only given via a cheat are then also gone again.":
        "此界面提供了多种通用设置来配置您在 Bondage Club 的体验, 例如启用/禁用打字指示器, 当您正在公共聊天中输入内容或仅向他们私语时, 该指示器会向其他 BCX 用户显示一个图标.作弊仅在设置期间暂时有效；仅通过作弊获得的物品随后也会再次消失.",
    "On this screen you can establish new rules for the player by simply clicking any rule template. After clicking on it, you can edit the rule's configuration. Purple rule templates indicate, that they are already in use; greyed out ones, that you have no access to them due to being blocked or due to your permission settings. Rule templates can be limited/blocked via the settings button on the very right. Note: If you want to be able to log rule violations, this type of log entry may need to be allowed in the configuration page of the behavior log module.":
        "在这个界面上, 您只需点击任何规则模板即可为玩家制定新规则.点击后, 您可以编辑规则的配置.紫色的规则模板表示它们已在使用中；灰色的规则模板表示由于被阻止或您的权限设置, 您无法访问它们.通过最右侧的设置按钮可以限制/阻止规则模板.注意：如果您希望能够记录规则违规情况, 可能需要在行为日志模块的配置页面中允许这种类型的日志条目.",
    "Here you can switch the curse on/off, set a timer for activating/deactivating/deleting the curse and define when it can trigger, such as either always or based on where the player is and with whom. The small green/red bars next to the checkboxes indicate whether a condition is true at present or not and the big bar whether this means that the curse is in effect, if active. On the right side, you can curse the usage/alteration of an item such as fixing cuffs behind the back. Lastly, in the bottom right you can set the trigger conditions of this curse to the global curses config.":
        "在这里, 您可以打开/关闭诅咒, 为激活/停用/删除诅咒设置计时器, 并定义其触发条件, 例如始终触发或基于玩家所在位置以及与谁在一起.复选框旁边的小绿/红条表示当前条件是否为真, 而大条表示如果处于激活状态, 该诅咒是否生效.在右侧, 您可以对诸如在背后固定袖口等物品的使用/更改进行诅咒.最后, 在右下角, 您可以将此诅咒的触发条件设置为全局诅咒配置.",
    "More": "更多",
    "More options [BCX]": "更多选项 [BCX]",
    "Standardize your room description so the room's purpose is clear and it can easily be filtered:":
        "标准化您的房间描述, 以便清晰显示房间的用途, 并且可以轻松进行过滤: ",
    "Create a theme room": "创建一个主题房间",
    "Templates for storing / overwriting current room information & settings (press a name to toggle auto-apply)":
        "用于存储/覆盖当前房间信息和设置的模板(按名称切换自动应用)",
    "- empty template slot -": "- 空模板槽 -",
    "Load": "加载",
    "    Save": "    保存",
    "1. Select the room type:": "1. 选择房间类型: ",
    "2. Optionally, select one room setting:": "2. 可选地, 选择一个房间设置: ",
    "3. Optionally, select limits for the room:": "3. 可选地, 选择房间的限制: ",
    "4. Optionally, write a room introduction message/greeting that everyone joining will see as emote:":
        "4. 可选地, 编写一个房间介绍消息/欢迎词, 所有加入的人都会看到其作为表情. ",
    "AFK/Storage": "AFK/存储",
    "Chill/Chat": "休闲/聊天",
    "Tying all up": "全部捆绑",
    "Game": "游戏",
    "Roleplaying": "角色扮演",
    "Kidnap/Danger": "绑架/危险",
    "Market/Auction": "市场/拍卖",
    "Undefined": "未定义",
    "Adventure": "冒险",
    "Historic": "历史",
    "Romantic": "浪漫",
    "SciFi": "科幻",
    "Fantasy": "奇幻",
    "Modern": "现代",
    "School": "学校",
    "no-anal": "无屁眼交易",
    "no-animals": "无动物",
    "no-fantasy": "无幻想",
    "no-limits": "无限制",
    "no-males": "无男性",
    "no-sexual": "无性行为",
    "no-tentacles": "无触手",
    "Blocked items:": "已屏蔽的物品:",
    "OK": "确定",
    "Import everything onscreen": "导入界面上的所有内容",
    "Export everything onscreen": "导出界面上的所有内容",
    "Hierachy of roles": "角色权限结构",
    "[Log message deleted]": "[日志消息已删除]",

  
    // EBCH
    "EBCH: Turn on Ungarble (Hearing Whitelist)": "EBCH: 打开去噪(听觉白名单)",
    "EBCH: Turn off custom notifications": "EBCH: 关闭自定义通知",
    "EBCH: Turn on chatlogging": "EBCH: 打开聊天记录",
    "EBCH: Turn on Ungarble (all)": "EBCH: 打开去噪(全部)",
    "EBCH: Turn on custom notifications": "EBCH: 打开自定义通知",
    "EBCH: Turn off ungarble": "EBCH: 关闭去噪",
    "EBCH: Preparing DB.": "EBCH: 准备数据库.",
    "EBCH: DB Ready.": "EBCH: 数据库准备就绪.",
    "EBCH: Turn off chatlogging": "EBCH: 关闭聊天记录",
    "EBCH: Pose UI on": "EBCH: 打开POSE UI",
    "BaseHand": "基础手势",
    "HandsUp": "举手",
    "HandsHigh": "高举双手",
    "BackLoose": "轻松背手",
    "BackTight": "紧绷背手",
    "Standing": "站立",
    "Kneeling": "跪姿",
    "KneelSpr": "跪地张腿",
    "StandCl": "站立闭合",
    "StandSpr": "站立张退",
    "BellyLie": "仰卧",
    "AllFours": "四肢着地",
    "EBCH: Pose UI off": "EBCH: 关闭POSE UI",
    "Base Hands": "基础手势",
    "Hands Up": "举手",
    "Hands Up High": "高举双手",
    "Back Loose": "轻松背手",
    "Back Tight": "紧绷背手",
    "Stand": "站立",
    "Kneel": "跪姿",
    "Kneel Spread": "跪地张腿",
    "Standing Closed Legs": "站立闭合腿",
    "Standing Spread": "站立张腿",
    "Belly Lie": "仰卧",
    "All Fours": "四肢着地",
};

export { translation };
