const translation = {
    // MBS
    "Configure the Wheel of Fortune": "配置幸运转盘",
    "Allow wheel spinning while restrainted": "允许转盘在约束下旋转",
    "Lock MBS settings while restrained": "受限状态下锁定MBS设置",
    "Select custom wheel of fortune item sets: page 0": "选择自定义幸运转盘道具套装: 第0页",
    "Select custom wheel of fortune item sets: page 1": "选择自定义幸运转盘道具套装: 第1页",
    "Select custom wheel of fortune commands: page 0": "选择自定义转盘指令: 第0页",
    "Select custom wheel of fortune commands: page 1": "选择自定义转盘指令: 第1页",
    "Reset": "重置",
    "Latest Changes": "最新更改",
    "Configure Wheel of Fortune": "配置幸运之轮",
    "0: Empty": "0: 空",
    "1: Empty": "1: 空",
    "2: Empty": "2: 空",
    "3: Empty": "3: 空",
    "4: Empty": "4: 空",
    "5: Empty": "5: 空",
    "6: Empty": "6: 空",
    "7: Empty": "7: 空",
    "8: Empty": "8: 空",
    "9: Empty": "9: 空",
    "10: Empty": "10: 空",
    "11: Empty": "11: 空",
    "12: Empty": "12: 空",
    "13: Empty": "13: 空",
    "14: Empty": "14: 空",
    "15: Empty": "15: 空",
    "item sets: page 1": "道具套装: 第1页",
    "commands: page 1": "指令: 第1页",
    "Exit": "退出",
    "16: Empty": "16: 空",
    "17: Empty": "17: 空",
    "18: Empty": "18: 空",
    "19: Empty": "19: 空",
    "20: Empty": "20: 空",
    "21: Empty": "21: 空",
    "22: Empty": "22: 空",
    "23: Empty": "23: 空",
    "24: Empty": "24: 空",
    "25: Empty": "25: 空",
    "26: Empty": "26: 空",
    "27: Empty": "27: 空",
    "28: Empty": "28: 空",
    "29: Empty": "29: 空",
    "30: Empty": "30: 空",
    "31: Empty": "31: 空",
    "commands: page 0": "指令: 第0页",
    "item sets: page 0": "道具套装: 第0页",
    "Clear all MBS data": "清除所有MBS数据",
    "Open the MBS changelog": "打开MBS更改日志",
    "Parse": "解析",
    "Clothes and underwear": "衣服和内衣",
    "Clothes, underwear and cosplay items": "衣服、内衣和角色扮演道具",
    "Accept: Missing outfit": "接受:缺少服装",
    "Delete": "删除",
    "Missing outfit code": "缺少服装代码",
    "Accept: Missing name": "接受:缺少名称",
    "Export MBS settings": "导出 MBS 设置",
    "Import MBS settings": "导入 MBS 设置",
    "Reset MBS": "重置 MBS",
    "Filter by item group": "按项目组筛选",
    "Select All": "全选",
    "Select None": "取消全选",
    "Preview female - only items: Page 1 / 1": "仅预览女性物品:第 1 页 / 1",
    "Filter by BC version": "按 BC 版本筛选",
    "Version R102": "版本 R102",
    "All versions": "所有版本",
    "Show item group filter": "显示项目组筛选",
    "Preview female - only items: Page 1 / 122": "仅预览女性物品:第 1 页 / 122",
    "Use item": "使用物品",
    "Change item color": "更改物品颜色",
    "Shop mode: Preview": "商店模式:预览",
    "Buy female - only items: Page 1 / 1": "购买仅限女性物品:第 1 页 / 1",
    "Shop mode: Buy": "商店模式:购买",
    "Sell female - only items: Page 1 / 1": "出售仅限女性物品:第 1 页 / 1",
    "Shop mode: Sell": "商店模式: 出售",

    "FetishShare": "癖好分享",
    "Fetish & Activity Settings": "癖好&动作喜好设置",
    "Fetishes": "癖好",
    "Fetish & Activity Compatibility:": "癖好&动作喜好相似度: ",
    "Always read bios and ask for consent & limits. Users might not keep these up to date.": "始终阅读个人简介并征求同意和了解限制. 用户可能不会及时更新这些信息.",
    "Activities (done to/by 她)": "动作喜好（对她所做/由她所做）",
    "Hide neutral activities": "隐藏 无所谓的动作",
    "Hide self-only activities": "隐藏 自己喜好做的动作",
    "Show compatibility percentage in chat rooms": "在聊天室中显示癖好相似度",
    "(Not recommended) Opt-out of others seeing your fetishes & activities through this plugin.": "(不推荐) 选择不让其他人通过此插件看到您的癖好&动作.",
    "Fetishes: N/A ｜ Activities: N/A": "癖好: N/A ｜ 动作: N/A",
};

export { translation };
