import AssetManager from "@mod-utils/AssetManager";
import { VersionSupport } from "@mod-utils/VersionSupport";

/** @type { CustomGroupedAssetDefinitions }} */
const assets = {
    新前发_Luzi: [
        {
            Name: "前发1",
            Random: false,
            Left: 50,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
        {
            Name: "前发2",
            Random: false,
            Left: 50,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
        {
            Name: "前发3",
            Random: false,
            Left: 50,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
        {
            Name: "前发4",
            Random: false,
            Left: 50,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
        {
            Name: "前发5",
            Random: false,
            Left: 50,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
        {
            Name: "前发6",
            Random: false,
            Left: 0,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
        {
            Name: "前发7",
            Random: false,
            Left: 0,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
        {
            Name: "前发8",
            Random: false,
            Left: 0,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
            Layer: [
                {
                    Name: "底",
                    Priority: 52,
                },
                {
                    Name: "高光",
                    Priority: 52,
                },
            ],
        },
        {
            Name: "前发9",
            Random: false,
            Left: 0,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
        {
            Name: "前发10",
            Random: false,
            Left: 0,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
        {
            Name: "前发11",
            Random: false,
            Left: 0,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
            Layer: [
                {
                    Name: "底",
                    Priority: 52,
                },
                {
                    Name: "高光",
                    Priority: 52,
                },
            ],
        },
        {
            Name: "前发12",
            Random: false,
            Left: 50,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
            Layer: [
                {
                    Name: "前",
                    Priority: 52,
                },
                {
                    Name: "后",
                    Priority: 5,
                },
            ],
        },
        {
            Name: "前发13",
            Random: false,
            Left: 50,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
        {
            Name: "前发14",
            Random: false,
            Left: 50,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
        {
            Name: "前发15",
            Random: false,
            Left: 50,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
        {
            Name: "前发16",
            Random: false,
            Left: 50,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
        {
            Name: "前发17",
            Random: false,
            Left: 50,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
        {
            Name: "前发18",
            Random: false,
            Left: 50,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
        {
            Name: "前发19",
            Random: false,
            Left: 50,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
        {
            Name: "前发20",
            Random: false,
            Left: 0,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
        {
            Name: "前发21",
            Random: false,
            Left: 0,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
        {
            Name: "前发22",
            Random: false,
            Left: 0,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
        {
            Name: "前发23",
            Random: false,
            Left: 0,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
        {
            Name: "前发24",
            Random: false,
            Left: 0,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
        {
            Name: "卷发1",
            Random: false,
            Left: 0,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
        {
            Name: "卷发2",
            Random: false,
            Left: 0,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
        {
            Name: "卷发3",
            Random: false,
            Left: 0,
            Top: 0,
            Priority: 52,
            ParentGroup: VersionSupport.NoParentGroup,
            Extended: false,
            InheritColor: "HairFront",
            Hide: ["HairFront"],
        },
    ],
};

/** @type { Translation.GroupedEntries } */
const translations = {
    CN: {
        新前发_Luzi: {
            前发1: "前发 1",
            前发2: "前发 2",
            前发3: "前发 3",
            前发4: "前发 4",
            前发5: "前发 5",
            前发6: "前发 6",
            前发7: "前发 7",
            前发8: "前发 8",
            前发9: "前发 9",
            前发10: "前发 10",
            前发11: "前发 11",
            前发12: "前发 12",
            前发13: "前发 13",
            前发14: "前发 14",
            前发15: "前发 15",
            前发16: "前发 16",
            前发17: "前发 17",
            前发18: "前发 18",
            前发19: "前发 19",
            前发20: "前发 20",
            前发21: "前发 21",
            前发22: "前发 22",
            前发23: "前发 23",
            前发24: "前发 24",
            卷发1: "卷发 1",
            卷发2: "卷发 2",
            卷发3: "卷发 3",
        },
    },
    EN: {
        新前发_Luzi: {
            前发1: "HairFront 1",
            前发2: "HairFront 2",
            前发3: "HairFront 3",
            前发4: "HairFront 4",
            前发5: "HairFront 5",
            前发6: "HairFront 6",
            前发7: "HairFront 7",
            前发8: "HairFront 8",
            前发9: "HairFront 9",
            前发10: "HairFront 10",
            前发11: "HairFront 11",
            前发12: "HairFront 12",
            前发13: "HairFront 13",
            前发14: "HairFront 14",
            前发15: "HairFront 15",
            前发16: "HairFront 16",
            前发17: "HairFront 17",
            前发18: "HairFront 18",
            前发19: "HairFront 19",
            前发20: "HairFront 20",
            前发21: "HairFront 21",
            前发22: "HairFront 22",
            前发23: "HairFront 23",
            前发24: "HairFront 24",
            卷发1: "Curly Hair 1",
            卷发2: "Curly Hair 2",
            卷发3: "Curly Hair 3"
        },
    },
};

export default function () {
    AssetManager.addGroupedAssets(assets, translations);
}
